// Copyright:
//   - Copyright © 2026 Alberto Villa Osorno.
// SPDX-License-Identifier:
//   - MIT
// Confidential:
//   - false
// License-File:
//   - LICENSE-MIT
//
// Boundary-Contract:
// - Owns:
//   - Deterministic Malbolge decompilation into readable executable C23.
// - Must-Not:
//   - Claim recovery of original C source or weaken selected-profile semantics.
// - Allows:
//   - Inputs: source admitted by one explicit canonical Malbolge profile.
//   - Outputs: caller-owned C source text and initial normalized decode
//   - comments.
//   - Side effects: process-local allocation only.
// - Split-When:
//   - Split when another output language gains an independent rendering model.
// - Merge-When:
//   - Merge when a general reverse-engineering IR owns the same projection.
// - Summary:
//   - Emits readable C that preserves profile-driven Malbolge machine behavior.
// - Description:
//   - Specializes the normative machine around one validated source artifact.
// - Usage:
//   - Called by `malbolge_decompile` and the museum conversion helper.
// - Defaults:
//   - Source/profile selection is explicit; generated C owns no host I/O
//   - policy.
//

//! Deterministic Malbolge-to-C decompilation backend.

use std::fmt::{Display, Formatter, Result as FormatResult, Write as _};

use malbolge::{ProfileDescriptor, ProfileKind, ProfileMachineError};

use super::analysis::{AnalysisError, InitialCell, analyze_initial};

const C_TEMPLATE: &str = r#"/* Generated by Malbolge decompiler. */
/* Profile: @PROFILE_ID@ @PROFILE_VERSION@ */
/* Fingerprint: @PROFILE_FINGERPRINT@ */
/* This is semantic C, not recovered original source. */

#include <stddef.h>
#include <stdint.h>

#define MB_WORD_MODULUS UINT32_C(@WORD_MODULUS@)
#define MB_MEMORY_WORDS UINT32_C(@MEMORY_WORDS@)
#define MB_EOF_WORD UINT32_C(@EOF_WORD@)
#define MB_INPUT_INSTRUCTION UINT32_C(@INPUT_INSTRUCTION@)
#define MB_OUTPUT_INSTRUCTION UINT32_C(@OUTPUT_INSTRUCTION@)
#define MB_NON_GRAPHICAL_NO_PROGRESS @NON_GRAPHICAL_NO_PROGRESS@
#define MB_WORD_TRITS UINT32_C(@WORD_TRITS@)
#define MB_GRAPHICAL_MIN UINT32_C(33)
#define MB_GRAPHICAL_MAX UINT32_C(126)
#define MB_DECODE_MODULUS UINT32_C(94)

@INITIAL_LISTING@

static const uint8_t MB_SOURCE[] = {
@SOURCE_BYTES@
};

static const uint8_t MB_TRANSLATION[] =
    "+b(29e*j1VMEKLyC})8&m#~W>qxdRp0wkrUo[D7,XTcA\"lI"
    ".v%{gJh4G\\-=O@5`_3i<?Z';FNQuY]szf$!BS/|t:Pn6^Ha";

static const uint8_t MB_ENCRYPTION[] =
    "5z]&gqtyfr$(we4{WP)H-Zn,[%\\3dL+Q;>U!pJS72FhOA1C"
    "B6v^=I_0/8|jsb9m<.TVac`uY*MK'X~xDl}REokN:#?G\"i@";

enum mb_status {
    MB_STATUS_BUDGET_EXHAUSTED = 0,
    MB_STATUS_HALT = 1,
    MB_STATUS_NON_GRAPHICAL = 2,
    MB_STATUS_INVALID_ENCRYPTION = 3,
    MB_STATUS_INVALID_ARGUMENT = 4,
    MB_STATUS_OUTPUT_EXHAUSTED = 5
};

struct mb_result {
    uint32_t accumulator;
    uint32_t code_pointer;
    uint32_t data_pointer;
    size_t input_consumed;
    size_t output_len;
    size_t steps;
    enum mb_status status;
};

static uint32_t mb_successor(uint32_t value)
{
    return value + UINT32_C(1) == MB_WORD_MODULUS
        ? UINT32_C(0)
        : value + UINT32_C(1);
}

static uint32_t mb_rotate(uint32_t value)
{
    const uint32_t low_trit = value % UINT32_C(3);
    return value / UINT32_C(3)
        + low_trit * (MB_WORD_MODULUS / UINT32_C(3));
}

static uint32_t mb_crazy(uint32_t data, uint32_t accumulator)
{
    static const uint8_t table[3][3] = {
        {1, 0, 0},
        {1, 0, 2},
        {2, 2, 1}
    };
    uint32_t result = UINT32_C(0);
    uint32_t place = UINT32_C(1);
    uint32_t trit = UINT32_C(0);
    while (trit < MB_WORD_TRITS) {
        const uint32_t data_trit = data % UINT32_C(3);
        const uint32_t accumulator_trit = accumulator % UINT32_C(3);
        result += (uint32_t)table[data_trit][accumulator_trit] * place;
        place *= UINT32_C(3);
        data /= UINT32_C(3);
        accumulator /= UINT32_C(3);
        ++trit;
    }
    return result;
}

static int mb_graphical(uint32_t value)
{
    return value >= MB_GRAPHICAL_MIN && value <= MB_GRAPHICAL_MAX;
}

static uint32_t mb_encrypted(uint32_t value)
{
    return (uint32_t)MB_ENCRYPTION[value - MB_GRAPHICAL_MIN];
}

uint32_t malbolge_decompiled_memory_words(void)
{
    return MB_MEMORY_WORDS;
}

int malbolge_decompiled_run(
    uint32_t *memory,
    size_t memory_words,
    const uint8_t *input,
    size_t input_len,
    uint8_t *output,
    size_t output_capacity,
    size_t step_budget,
    struct mb_result *result)
{
    const size_t source_len = sizeof(MB_SOURCE) / sizeof(MB_SOURCE[0]);
    uint32_t accumulator = UINT32_C(0);
    uint32_t code_pointer = UINT32_C(0);
    uint32_t data_pointer = UINT32_C(0);
    size_t input_cursor = 0;
    size_t output_len = 0;
    size_t steps = 0;
    enum mb_status status = MB_STATUS_BUDGET_EXHAUSTED;
    size_t index = 0;

    if (result != NULL) {
        result->accumulator = UINT32_C(0);
        result->code_pointer = UINT32_C(0);
        result->data_pointer = UINT32_C(0);
        result->input_consumed = 0;
        result->output_len = 0;
        result->steps = 0;
        result->status = MB_STATUS_INVALID_ARGUMENT;
    }
    if (memory == NULL || result == NULL
        || memory_words != (size_t)MB_MEMORY_WORDS
        || (input_len != 0 && input == NULL)
        || (output_capacity != 0 && output == NULL)) {
        return (int)MB_STATUS_INVALID_ARGUMENT;
    }

    for (index = 0; index < source_len; ++index) {
        memory[index] = (uint32_t)MB_SOURCE[index];
    }
    for (index = source_len; index < memory_words; ++index) {
        memory[index] = mb_crazy(memory[index - 2], memory[index - 1]);
    }

    while (steps < step_budget) {
        const uint32_t cell = memory[code_pointer];
        uint32_t next_accumulator = accumulator;
        uint32_t next_code_pointer = code_pointer;
        uint32_t next_data_pointer = data_pointer;
        uint32_t write_address = UINT32_C(0);
        uint32_t write_value = UINT32_C(0);
        uint32_t encryption_target = UINT32_C(0);
        uint32_t encrypted = UINT32_C(0);
        uint8_t output_byte = UINT8_C(0);
        int consumes_input = 0;
        int emits_output = 0;
        int writes_memory = 0;
        uint32_t decoded = UINT32_C(0);

        if (!mb_graphical(cell)) {
            ++steps;
            if (MB_NON_GRAPHICAL_NO_PROGRESS != 0) {
                continue;
            }
            status = MB_STATUS_NON_GRAPHICAL;
            break;
        }
        decoded = (uint32_t)MB_TRANSLATION[
            (cell - MB_GRAPHICAL_MIN
                + (code_pointer % MB_DECODE_MODULUS))
            % MB_DECODE_MODULUS
        ];
        if (decoded == (uint32_t)'v') {
            ++steps;
            status = MB_STATUS_HALT;
            break;
        }

        switch (decoded) {
        case 'i':
            next_code_pointer = memory[data_pointer];
            break;
        case MB_INPUT_INSTRUCTION:
            consumes_input = 1;
            break;
        case MB_OUTPUT_INSTRUCTION:
            output_byte = (uint8_t)(accumulator % UINT32_C(256));
            emits_output = 1;
            break;
        case '*':
            write_address = data_pointer;
            write_value = mb_rotate(memory[data_pointer]);
            next_accumulator = write_value;
            writes_memory = 1;
            break;
        case 'j':
            next_data_pointer = memory[data_pointer];
            break;
        case 'p':
            write_address = data_pointer;
            write_value = mb_crazy(memory[data_pointer], accumulator);
            next_accumulator = write_value;
            writes_memory = 1;
            break;
        case 'o':
        default:
            break;
        }

        encryption_target = writes_memory
            && write_address == next_code_pointer
            ? write_value
            : memory[next_code_pointer];
        if (!mb_graphical(encryption_target)) {
            status = MB_STATUS_INVALID_ENCRYPTION;
            break;
        }
        encrypted = mb_encrypted(encryption_target);
        if (emits_output && output_len >= output_capacity) {
            status = MB_STATUS_OUTPUT_EXHAUSTED;
            break;
        }

        if (consumes_input) {
            if (input_cursor < input_len) {
                next_accumulator = (uint32_t)input[input_cursor];
                ++input_cursor;
            } else {
                next_accumulator = MB_EOF_WORD;
            }
        }
        if (writes_memory && write_address != next_code_pointer) {
            memory[write_address] = write_value;
        }
        memory[next_code_pointer] = encrypted;
        accumulator = next_accumulator;
        code_pointer = mb_successor(next_code_pointer);
        data_pointer = mb_successor(next_data_pointer);
        if (emits_output) {
            output[output_len] = output_byte;
            ++output_len;
        }
        ++steps;
    }

    result->accumulator = accumulator;
    result->code_pointer = code_pointer;
    result->data_pointer = data_pointer;
    result->input_consumed = input_cursor;
    result->output_len = output_len;
    result->steps = steps;
    result->status = status;
    return (int)status;
}
"#;

/// Deterministic decompilation failure.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DecompileError {
    /// Input source is invalid for the explicitly selected profile.
    InvalidSource(ProfileMachineError),
    /// Validated source position unexpectedly cannot fit the profile address
    /// type.
    PositionOverflow,
    /// Rendering into the owned String unexpectedly reported formatting
    /// failure.
    Rendering,
}

impl Display for DecompileError {
    fn fmt(&self, f: &mut Formatter<'_>) -> FormatResult {
        match self {
            Self::InvalidSource(error) => write!(f, "invalid source: {error}"),
            Self::PositionOverflow => f.write_str("source position overflow"),
            Self::Rendering => f.write_str("representation rendering failed"),
        }
    }
}

impl From<AnalysisError> for DecompileError {
    fn from(error: AnalysisError) -> Self {
        match error {
            AnalysisError::InvalidSource(source) => Self::InvalidSource(source),
            AnalysisError::PositionOverflow => Self::PositionOverflow,
        }
    }
}

/// Renders typed initial-state reverse-engineering annotations.
///
/// This report deliberately leaves indirect targets unresolved and does not
/// predict decoding after self-modification.
///
/// # Errors
///
/// Returns a deterministic [`DecompileError`] when source admission, position
/// conversion, or owned-string rendering fails.
pub fn render_analysis(
    profile: &'static ProfileDescriptor,
    source: &[u8],
) -> Result<String, DecompileError> {
    let analysis =
        analyze_initial(profile, source).map_err(DecompileError::from)?;
    let mut output = String::from(
        "Malbolge initial-state analysis
",
    );
    writeln!(&mut output, "profile_id={}", analysis.profile_id())
        .map_err(|_error| DecompileError::Rendering)?;
    writeln!(
        &mut output,
        "profile_version={}",
        analysis.profile_version()
    )
    .map_err(|_error| DecompileError::Rendering)?;
    writeln!(
        &mut output,
        "profile_fingerprint={}",
        analysis.profile_fingerprint(),
    )
    .map_err(|_error| DecompileError::Rendering)?;
    output.push_str(
        "limitations=initial-state-only;indirect-targets=unresolved;",
    );
    output.push_str(
        "self-modification=invalidates-static-decode
",
    );
    for cell in analysis.cells() {
        writeln!(
            &mut output,
            concat!(
                "cell position={} raw={} decoded={} control={} data={} ",
                "accumulator={} post_step_encryption={}"
            ),
            cell.position,
            cell.raw,
            char::from(cell.decoded),
            cell.control_flow.as_str(),
            cell.data.as_str(),
            cell.accumulator.as_str(),
            if cell.post_step_encryption {
                "yes"
            } else {
                "no"
            },
        )
        .map_err(|_error| DecompileError::Rendering)?;
    }
    Ok(output)
}

/// Renders one validated Malbolge source as readable executable C23.
///
/// The output is a semantics-preserving specialized machine, not a claim that
/// the original human-authored C source can be reconstructed from Malbolge.
///
/// # Errors
///
/// Returns [`DecompileError::InvalidSource`] when `source` is not admitted by
/// `profile`, [`DecompileError::PositionOverflow`] on impossible position
/// conversion failure after validation, or [`DecompileError::Rendering`] if the
/// owned output buffer unexpectedly rejects formatting.
pub fn render_c(
    profile: &'static ProfileDescriptor,
    source: &[u8],
) -> Result<String, DecompileError> {
    let analysis =
        analyze_initial(profile, source).map_err(DecompileError::from)?;
    let listing = initial_listing(profile, analysis.cells())?;
    let bytes = source_bytes(analysis.source())?;
    Ok(C_TEMPLATE
        .replace("@PROFILE_ID@", profile.id())
        .replace("@PROFILE_VERSION@", profile.version())
        .replace("@PROFILE_FINGERPRINT@", profile.fingerprint())
        .replace("@WORD_MODULUS@", &profile.word_modulus().to_string())
        .replace("@MEMORY_WORDS@", &profile.memory_words().to_string())
        .replace("@EOF_WORD@", &profile.eof_word().to_string())
        .replace(
            "@INPUT_INSTRUCTION@",
            &profile.input_instruction().to_string(),
        )
        .replace(
            "@OUTPUT_INSTRUCTION@",
            &profile.output_instruction().to_string(),
        )
        .replace(
            "@NON_GRAPHICAL_NO_PROGRESS@",
            if profile.kind() == ProfileKind::HistoricalConformance {
                "1"
            } else {
                "0"
            },
        )
        .replace("@WORD_TRITS@", &profile.word_trits().to_string())
        .replace("@INITIAL_LISTING@", &listing)
        .replace("@SOURCE_BYTES@", &bytes))
}

fn initial_listing(
    profile: &ProfileDescriptor,
    cells: &[InitialCell],
) -> Result<String, DecompileError> {
    let mut output = String::from(
        "/* Initial normalized decode:
",
    );
    for cell in cells {
        let name = decoded_name(profile, cell.decoded);
        writeln!(
            &mut output,
            " * {:>8}: {:>3} -> {name}",
            cell.position, cell.raw,
        )
        .map_err(|_error| DecompileError::Rendering)?;
    }
    output.push_str(" */");
    Ok(output)
}

const fn decoded_name(
    profile: &ProfileDescriptor,
    decoded: u8,
) -> &'static str {
    if decoded == profile.input_instruction() {
        return match decoded {
            b'/' => "/  input byte into A",
            b'<' => "<  input byte into A",
            _ => "?  invalid profile input instruction",
        };
    }
    if decoded == profile.output_instruction() {
        return match decoded {
            b'/' => "/  output low byte of A",
            b'<' => "<  output low byte of A",
            _ => "?  invalid profile output instruction",
        };
    }
    match decoded {
        b'i' => "i  jump code pointer from [D]",
        b'*' => "*  rotate [D] into A and [D]",
        b'j' => "j  load D from [D]",
        b'p' => "p  crazy [D], A into A and [D]",
        b'o' => "o  no-op",
        b'v' => "v  halt",
        _ => "?  invalid initial instruction",
    }
}

fn source_bytes(source: &[u8]) -> Result<String, DecompileError> {
    let mut output = String::new();
    let mut chunks = source.chunks(12).peekable();
    while let Some(chunk) = chunks.next() {
        output.push_str("    ");
        let mut bytes = chunk.iter().copied().peekable();
        while let Some(byte) = bytes.next() {
            write!(&mut output, "UINT8_C({byte})")
                .map_err(|_error| DecompileError::Rendering)?;
            if bytes.peek().is_some() || chunks.peek().is_some() {
                output.push_str(", ");
            }
        }
        output.push('\n');
    }
    Ok(output)
}
