domain = "tools"
schema_version = 1

[entry.basedpyright]
path = ".dependencies/python/3.14.6/jig-bin/basedpyright.bin"

[entry.chktex.linux]
path = ".dependencies/bin/chktex"

[entry.git]
path = ".dependencies/git/2.55.0/bin/git.bin"

[entry.latexmk.linux]
path = ".dependencies/bin/latexmk"

[entry.pytest]
path = ".dependencies/python/3.14.6/jig-bin/pytest.bin"

[entry.ruff]
path = ".dependencies/python/3.14.6/jig-bin/ruff.bin"

[entry.rust_nightly_cargo_clippy]
path = ".dependencies/rust/nightly-2026-07-14/bin/cargo-clippy.bin"

[entry.rust_nightly_cargo_fmt]
path = ".dependencies/rust/nightly-2026-07-14/bin/cargo-fmt.bin"

[entry.rust_stable_cargo]
path = ".dependencies/rust/1.97.1/bin/cargo.bin"
