# Copyright:
#   - Copyright © 2026 Alberto Villa Osorno.
# SPDX-License-Identifier:
#   - MIT
# Confidential:
#   - false
# License-File:
#   - LICENSE-MIT
#
# Boundary-Contract:
# - Owns:
#   - Dense normalizer-free and exact rank/unrank for the double-transposition
#     stabilizer in the top-level all-equal S6 residual stratum.
# - Must-Not:
#   - Claim dense rank for another exact full-S6 stabilizer type.
# - Allows:
#   - Inputs: H-fixed residual assignments for H generated by (23)(45).
#   - Outputs: free N(H)/H ranks, exact-H ranks, and complete outer ranks.
#   - Side effects: none.
# - Split-When:
#   - The two bounded nonnormalizing extension families need reusable ranks.
# - Merge-When:
#   - Complete dense full-S6 ranking owns every exact stabilizer stratum.
# - Summary:
#   - Rank the order-eight normalizer quotient and skip 8,773 exact extensions.
# - Description:
#   - Exact extensions are S3 on 3+3 vertices or D10 on 5+1 vertices.
# - Usage:
#   - Constructive rank for the second-largest proper symmetric S6 type.
# - Defaults:
#   - Exact residual and complete rank/unrank reach total mass fourteen.
#

"""Dense exact rank for the full-S6 double-transposition stabilizer."""

from __future__ import annotations

from bisect import bisect_left
from collections import deque
from functools import cache
from itertools import permutations
from typing import cast

_ARITY = 6
_MAXIMUM_MASS = 14
_EXHAUSTIVE_MASS = 5
_H_ORDER = 2
_NORMALIZER_ORDER = 16
_QUOTIENT_ORDER = 8
_EXPECTED_QUOTIENT_SUBGROUPS = 16
_EXPECTED_EXCEPTION_GROUPS = 4
_EXPECTED_H_ORBIT_SIZES = {1: 12, 2: 20}
_EXPECTED_BLOCK_SIZES = (4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2)
_EXPECTED_BLOCK_WEIGHTS = (1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2)
_EXPECTED_FREE_COUNTS = (
    0,
    0,
    0,
    6,
    60,
    424,
    2_274,
    10_408,
    41_818,
    152_452,
    511_870,
    1_606_062,
    4_750_838,
    13_354_968,
    35_878_792,
)
_EXPECTED_EXACT_COUNTS = (
    0,
    0,
    0,
    5,
    55,
    406,
    2_223,
    10_287,
    41_574,
    151_954,
    510_883,
    1_604_295,
    4_747_715,
    13_349_605,
    35_870_019,
)
_EXPECTED_S3_EXCEPTIONS = (
    0,
    0,
    0,
    1,
    5,
    14,
    43,
    109,
    228,
    478,
    940,
    1_693,
    3_022,
    5_235,
    8_618,
)
_EXPECTED_D10_EXCEPTIONS = (
    0,
    0,
    0,
    0,
    0,
    4,
    8,
    12,
    16,
    20,
    47,
    74,
    101,
    128,
    155,
)
_EXPECTED_COMPLETE_COUNTS = (
    0,
    0,
    0,
    5,
    55,
    406,
    2_223,
    10_287,
    41_574,
    151_964,
    510_993,
    1_605_107,
    4_752_161,
    13_370_179,
    35_953_167,
)


type _Permutation = tuple[int, int, int, int, int, int]
type _Group = frozenset[_Permutation]
type _Orbit = tuple[int, ...]
type _Block = tuple[int, ...]
type _Vector = tuple[int, ...]
type _LocalClass = tuple[_Block, int]
type _Pair = tuple[int, int]
type _State = tuple[_Pair, _Vector]
type _MassContext = tuple[int, int]
type _RankContext = tuple[int, int, int]
type _UnrankContext = tuple[int, int, int]

_IDENTITY: _Permutation = (0, 1, 2, 3, 4, 5)
_DOUBLE_TRANSPOSITION: _Permutation = (0, 1, 3, 2, 5, 4)
_H: _Group = frozenset({_IDENTITY, _DOUBLE_TRANSPOSITION})
_S6 = cast("tuple[_Permutation, ...]", tuple(permutations(range(_ARITY))))
_RESIDUAL_LABELS = tuple(
    symbol
    for symbol in range(1 << _ARITY)
    if symbol.bit_count() not in {1, _ARITY - 1}
)
_RESIDUAL_INDEX = {label: index for index, label in enumerate(_RESIDUAL_LABELS)}


def _compose(left: _Permutation, right: _Permutation) -> _Permutation:
    return cast(
        "_Permutation",
        tuple(left[right[index]] for index in range(_ARITY)),
    )


def _inverse(order: _Permutation) -> _Permutation:
    result = [0] * _ARITY
    for source, target in enumerate(order):
        result[target] = source
    return cast("_Permutation", tuple(result))


def _products(
    left: _Permutation, generators: tuple[_Permutation, ...]
) -> tuple[_Permutation, ...]:
    return tuple(
        product
        for right in generators
        for product in (_compose(left, right), _compose(right, left))
    )


@cache
def _generated(generators: tuple[_Permutation, ...]) -> _Group:
    generators = tuple(sorted(set(generators)))
    subgroup = {_IDENTITY}
    frontier = deque([_IDENTITY])
    while frontier:
        left = frontier.popleft()
        for product in _products(left, generators):
            if product not in subgroup:
                subgroup.add(product)
                frontier.append(product)
    return frozenset(subgroup)


def _minimal_generators(group: _Group) -> tuple[_Permutation, ...]:
    generators: list[_Permutation] = []
    generated = frozenset({_IDENTITY})
    for element in sorted(group):
        if element in generated:
            continue
        generators.append(element)
        generated = _generated(tuple(generators))
        if generated == group:
            break
    return tuple(generators)


def _conjugate(element: _Permutation, by: _Permutation) -> _Permutation:
    return _compose(_compose(by, element), _inverse(by))


_NORMALIZER = tuple(
    element
    for element in _S6
    if _conjugate(_DOUBLE_TRANSPOSITION, element) == _DOUBLE_TRANSPOSITION
)


def _permuted_symbol(symbol: int, order: _Permutation) -> int:
    bits = tuple(
        (symbol >> (_ARITY - endpoint - 1)) & 1 for endpoint in range(_ARITY)
    )
    result = 0
    for source in order:
        result = (result << 1) | bits[source]
    return result


@cache
def _residual_orbits(group: _Group) -> tuple[_Orbit, ...]:
    unseen = set(_RESIDUAL_LABELS)
    result: list[_Orbit] = []
    while unseen:
        seed = min(unseen)
        orbit = tuple(sorted({_permuted_symbol(seed, item) for item in group}))
        unseen -= set(orbit)
        result.append(orbit)
    return tuple(sorted(result, key=lambda orbit: (len(orbit), orbit)))


def _vertex_orbit_sizes(group: _Group) -> tuple[int, ...]:
    unseen = set(range(_ARITY))
    sizes: list[int] = []
    while unseen:
        seed = min(unseen)
        orbit = {order[seed] for order in group}
        unseen -= orbit
        sizes.append(len(orbit))
    return tuple(sorted(sizes, reverse=True))


_H_ORBITS = _residual_orbits(_H)
_H_ORBIT_INDEX = {orbit: index for index, orbit in enumerate(_H_ORBITS)}


def _image_h_orbit(orbit: _Orbit, order: _Permutation) -> _Orbit:
    return tuple(sorted(_permuted_symbol(symbol, order) for symbol in orbit))


_ACTIONS = tuple(
    sorted({
        tuple(
            _H_ORBIT_INDEX[_image_h_orbit(orbit, order)] for orbit in _H_ORBITS
        )
        for order in _NORMALIZER
    })
)
_ACTION_INDEX = {action: index for index, action in enumerate(_ACTIONS)}
_IDENTITY_ACTION = _ACTION_INDEX[tuple(range(len(_H_ORBITS)))]
_IDENTITY_GROUP = 1 << _IDENTITY_ACTION
_ALL_GROUP = (1 << len(_ACTIONS)) - 1


def _compose_action(left: int, right: int) -> int:
    return _ACTION_INDEX[
        tuple(
            _ACTIONS[left][_ACTIONS[right][index]]
            for index in range(len(_H_ORBITS))
        )
    ]


_MULTIPLICATION = tuple(
    tuple(_compose_action(left, right) for right in range(len(_ACTIONS)))
    for left in range(len(_ACTIONS))
)


def _group_elements(group: int) -> tuple[int, ...]:
    return tuple(
        element for element in range(len(_ACTIONS)) if group & (1 << element)
    )


def _q_products(left: int, generators: tuple[int, ...]) -> tuple[int, ...]:
    return tuple(
        product
        for right in generators
        for product in (
            _MULTIPLICATION[left][right],
            _MULTIPLICATION[right][left],
        )
    )


@cache
def _generated_q(generators: tuple[int, ...]) -> int:
    subgroup = {_IDENTITY_ACTION}
    frontier = deque([_IDENTITY_ACTION])
    generators = tuple(sorted(set(generators)))
    while frontier:
        left = frontier.popleft()
        for product in _q_products(left, generators):
            if product not in subgroup:
                subgroup.add(product)
                frontier.append(product)
    return sum(1 << element for element in subgroup)


def _minimal_q_generators(group: int) -> tuple[int, ...]:
    generators: list[int] = []
    generated = _IDENTITY_GROUP
    for element in _group_elements(group):
        if generated & (1 << element):
            continue
        generators.append(element)
        generated = _generated_q(tuple(generators))
    return tuple(generators)


@cache
def _all_q_subgroups() -> tuple[int, ...]:
    known = {_IDENTITY_GROUP}
    frontier = [_IDENTITY_GROUP]
    while frontier:
        group = frontier.pop()
        generators = _minimal_q_generators(group)
        for element in range(len(_ACTIONS)):
            if group & (1 << element):
                continue
            candidate = _generated_q((*generators, element))
            if candidate not in known:
                known.add(candidate)
                frontier.append(candidate)
    return tuple(sorted(known, key=lambda group: (-group.bit_count(), group)))


def _subgroups_of(group: int) -> tuple[int, ...]:
    return tuple(
        candidate for candidate in _all_q_subgroups() if candidate & ~group == 0
    )


def _q_blocks() -> tuple[tuple[int, ...], ...]:
    unseen = set(range(len(_H_ORBITS)))
    fixed: list[tuple[int, ...]] = []
    moving: list[tuple[int, ...]] = []
    while unseen:
        seed = min(unseen)
        orbit = tuple(sorted({action[seed] for action in _ACTIONS}))
        unseen -= set(orbit)
        if len(orbit) == 1:
            fixed.append(orbit)
        else:
            moving.append(orbit)
    fixed_block = tuple(item[0] for item in fixed)
    moving.sort(
        key=lambda block: (-len(block), len(_H_ORBITS[block[0]]), block)
    )
    return (fixed_block, *moving)


_BLOCK_LABELS = _q_blocks()
_BLOCK_SIZES = tuple(len(block) for block in _BLOCK_LABELS)
_BLOCK_WEIGHTS = tuple(len(_H_ORBITS[block[0]]) for block in _BLOCK_LABELS)
_BLOCK_COUNT = len(_BLOCK_LABELS)


@cache
def _block_mapping(block: int, element: int) -> tuple[int, ...]:
    labels = _BLOCK_LABELS[block]
    index = {label: position for position, label in enumerate(labels)}
    return tuple(index[_ACTIONS[element][label]] for label in labels)


def _apply_block(vector: _Block, block: int, element: int) -> _Block:
    mapping = _block_mapping(block, element)
    result = [0] * len(vector)
    for source, destination in enumerate(mapping):
        result[destination] = vector[source]
    return tuple(result)


@cache
def _compositions(total: int, parts: int) -> tuple[_Block, ...]:
    if parts == 1:
        return ((total,),)
    return tuple(
        (first, *suffix)
        for first in range(total + 1)
        for suffix in _compositions(total - first, parts - 1)
    )


def _stabilizer(vector: _Block, block: int, group: int) -> int:
    return sum(
        1 << element
        for element in _group_elements(group)
        if _apply_block(vector, block, element) == vector
    )


@cache
def _local_classes(
    block: int, mass: int, group: int
) -> tuple[_LocalClass, ...]:
    weight = _BLOCK_WEIGHTS[block]
    if mass % weight != 0:
        return ()
    scalar_mass = mass // weight
    if group == _IDENTITY_GROUP:
        return tuple(
            (vector, _IDENTITY_GROUP)
            for vector in _compositions(scalar_mass, _BLOCK_SIZES[block])
        )
    elements = _group_elements(group)
    result: list[_LocalClass] = []
    for vector in _compositions(scalar_mass, _BLOCK_SIZES[block]):
        representative = min(
            _apply_block(vector, block, element) for element in elements
        )
        if vector == representative:
            result.append((vector, _stabilizer(vector, block, group)))
    return tuple(result)


@cache
def _fixed_count(total: int, weights: tuple[int, ...]) -> int:
    coefficients = [1] + [0] * total
    for weight in weights:
        next_coefficients = [0] * (total + 1)
        for degree, coefficient in enumerate(coefficients):
            if coefficient == 0:
                continue
            for addition in range(0, total - degree + 1, weight):
                next_coefficients[degree + addition] += coefficient
        coefficients = next_coefficients
    return coefficients[total]


@cache
def _remaining_group_weights(block: int, group: int) -> tuple[int, ...]:
    elements = _group_elements(group)
    result: list[int] = []
    for candidate in range(block, _BLOCK_COUNT):
        unseen = set(range(_BLOCK_SIZES[candidate]))
        while unseen:
            seed = min(unseen)
            orbit = {
                _block_mapping(candidate, element)[seed] for element in elements
            }
            unseen -= orbit
            result.append(len(orbit) * _BLOCK_WEIGHTS[candidate])
    return tuple(sorted(result))


@cache
def _free_suffix_count(block: int, total: int, group: int) -> int:
    if block == _BLOCK_COUNT:
        return int(total == 0 and group == _IDENTITY_GROUP)
    exact: dict[int, int] = {}
    for subgroup in _subgroups_of(group):
        fixed = _fixed_count(total, _remaining_group_weights(block, subgroup))
        for larger, value in exact.items():
            if (
                larger.bit_count() > subgroup.bit_count()
                and subgroup & ~larger == 0
            ):
                fixed -= value
        assert fixed >= 0
        exact[subgroup] = fixed
    trivial_assignments = exact[_IDENTITY_GROUP]
    assert trivial_assignments % group.bit_count() == 0
    return trivial_assignments // group.bit_count()


def _block_mass(vector: _Block, block: int) -> int:
    return sum(vector) * _BLOCK_WEIGHTS[block]


def _block_mass_count(block: int, mass: int, context: _MassContext) -> int:
    suffix_mass, group = context
    return sum(
        _free_suffix_count(block + 1, suffix_mass, stabilizer)
        for _, stabilizer in _local_classes(block, mass, group)
    )


def _canonicalize_block(
    blocks: list[_Block], block: int, group: int
) -> tuple[_Block, int]:
    representative, chosen = min(
        (_apply_block(blocks[block], block, element), element)
        for element in _group_elements(group)
    )
    for index in range(block, _BLOCK_COUNT):
        blocks[index] = _apply_block(blocks[index], index, chosen)
    return representative, _stabilizer(representative, block, group)


def _extract_blocks(vector: _Vector) -> list[_Block] | None:
    if len(vector) != len(_H_ORBITS) or any(value < 0 for value in vector):
        return None
    return [
        tuple(vector[index] for index in labels) for labels in _BLOCK_LABELS
    ]


def _build_vector(blocks: tuple[_Block, ...]) -> _Vector:
    result = [0] * len(_H_ORBITS)
    for labels, block in zip(_BLOCK_LABELS, blocks, strict=True):
        for label, value in zip(labels, block, strict=True):
            result[label] = value
    return tuple(result)


def _vector_mass(vector: _Vector) -> int:
    return sum(
        value * len(orbit)
        for value, orbit in zip(vector, _H_ORBITS, strict=True)
    )


def _free_count(total: int) -> int:
    return _free_suffix_count(0, total, _ALL_GROUP)


def _free_rank_step(
    blocks: list[_Block], block: int, context: _RankContext
) -> tuple[int, int, int] | None:
    remaining_mass, group, rank = context
    mass = _block_mass(blocks[block], block)
    rank += sum(
        _block_mass_count(block, candidate, (remaining_mass - candidate, group))
        for candidate in range(mass)
    )
    representative, stabilizer = _canonicalize_block(blocks, block, group)
    for candidate, candidate_stabilizer in _local_classes(block, mass, group):
        count = _free_suffix_count(
            block + 1, remaining_mass - mass, candidate_stabilizer
        )
        if candidate != representative:
            rank += count
            continue
        if count == 0:
            return None
        return remaining_mass - mass, stabilizer, rank
    raise AssertionError


def _free_rank(vector: _Vector) -> int | None:
    blocks = _extract_blocks(vector)
    if blocks is None:
        return None
    context = (_vector_mass(vector), _ALL_GROUP, 0)
    for block in range(_BLOCK_COUNT):
        next_context = _free_rank_step(blocks, block, context)
        if next_context is None:
            return None
        context = next_context
    _, group, rank = context
    return rank if group == _IDENTITY_GROUP else None


def _choose_local_class(
    block: int, mass: int, context: _UnrankContext
) -> tuple[_Block, int, int] | None:
    remaining_mass, group, rank = context
    for vector, stabilizer in _local_classes(block, mass, group):
        count = _free_suffix_count(block + 1, remaining_mass - mass, stabilizer)
        if rank >= count:
            rank -= count
            continue
        return vector, stabilizer, rank
    return None


def _free_unrank_step(
    block: int, blocks: list[_Block], context: _UnrankContext
) -> _UnrankContext:
    remaining_mass, group, rank = context
    for mass in range(remaining_mass + 1):
        count = _block_mass_count(block, mass, (remaining_mass - mass, group))
        if rank >= count:
            rank -= count
            continue
        chosen = _choose_local_class(block, mass, (remaining_mass, group, rank))
        assert chosen is not None
        vector, stabilizer, rank = chosen
        blocks.append(vector)
        return remaining_mass - mass, stabilizer, rank
    raise AssertionError


def _free_unrank(total: int, rank: int) -> _Vector | None:
    if rank < 0 or rank >= _free_count(total):
        return None
    blocks: list[_Block] = []
    context = (total, _ALL_GROUP, rank)
    for block in range(_BLOCK_COUNT):
        context = _free_unrank_step(block, blocks, context)
    remaining_mass, group, rank = context
    assert remaining_mass == 0
    assert rank == 0
    assert group == _IDENTITY_GROUP
    return _build_vector(tuple(blocks))


def _exception_groups() -> tuple[tuple[_Group, ...], tuple[_Group, ...]]:
    s3: set[_Group] = set()
    d10: set[_Group] = set()
    normalizer = frozenset(_NORMALIZER)
    for element in _S6:
        group = _generated((_DOUBLE_TRANSPOSITION, element))
        if group & normalizer != _H:
            continue
        signature = len(group), _vertex_orbit_sizes(group)
        if signature == (6, (3, 3)):
            s3.add(group)
        elif signature == (10, (5, 1)):
            d10.add(group)
    return tuple(sorted(s3, key=tuple)), tuple(sorted(d10, key=tuple))


_S3_GROUPS, _D10_GROUPS = _exception_groups()


@cache
def _strict_extensions(group: _Group) -> tuple[tuple[_Orbit, ...], ...]:
    generators = _minimal_generators(group)
    extensions = {
        _generated((*generators, element))
        for element in _S6
        if element not in group
    }
    return tuple(
        _residual_orbits(extension)
        for extension in extensions
        if len(extension) > len(group)
    )


@cache
def _weighted_vectors(
    weights: tuple[int, ...], total: int
) -> tuple[_Vector, ...]:
    if len(weights) == 1:
        weight = weights[0]
        return ((total // weight,),) if total % weight == 0 else ()
    first = weights[0]
    return tuple(
        (value, *suffix)
        for value in range(total // first + 1)
        for suffix in _weighted_vectors(weights[1:], total - first * value)
    )


def _assignment(values: _Vector, orbits: tuple[_Orbit, ...]) -> _Vector:
    result = [0] * len(_RESIDUAL_LABELS)
    for value, orbit in zip(values, orbits, strict=True):
        for label in orbit:
            result[_RESIDUAL_INDEX[label]] = value
    return tuple(result)


def _fixed_by_orbits(values: _Vector, orbits: tuple[_Orbit, ...]) -> bool:
    return all(
        len({values[_RESIDUAL_INDEX[label]] for label in orbit}) == 1
        for orbit in orbits
    )


def _to_h_vector(values: _Vector) -> _Vector:
    return tuple(values[_RESIDUAL_INDEX[orbit[0]]] for orbit in _H_ORBITS)


@cache
def _exact_group_vectors(group: _Group, total: int) -> tuple[_Vector, ...]:
    orbits = _residual_orbits(group)
    weights = tuple(len(orbit) for orbit in orbits)
    extensions = _strict_extensions(group)
    result: list[_Vector] = []
    for orbit_values in _weighted_vectors(weights, total):
        values = _assignment(orbit_values, orbits)
        if any(_fixed_by_orbits(values, extension) for extension in extensions):
            continue
        result.append(_to_h_vector(values))
    return tuple(result)


@cache
def _exception_rank_sets(total: int) -> tuple[tuple[int, ...], tuple[int, ...]]:
    result: list[tuple[int, ...]] = []
    for groups in (_S3_GROUPS, _D10_GROUPS):
        ranks: set[int] = set()
        for group in groups:
            for vector in _exact_group_vectors(group, total):
                rank = _free_rank(vector)
                assert rank is not None
                ranks.add(rank)
        result.append(tuple(sorted(ranks)))
    return result[0], result[1]


@cache
def _exact_exclusions(total: int) -> tuple[int, ...]:
    s3, d10 = _exception_rank_sets(total)
    assert not set(s3) & set(d10)
    return tuple(sorted((*s3, *d10)))


def _exact_count(total: int) -> int:
    return _free_count(total) - len(_exact_exclusions(total))


def _exact_rank(vector: _Vector) -> int | None:
    free_rank = _free_rank(vector)
    if free_rank is None:
        return None
    exclusions = _exact_exclusions(_vector_mass(vector))
    index = bisect_left(exclusions, free_rank)
    if index < len(exclusions) and exclusions[index] == free_rank:
        return None
    return free_rank - index


def _exact_unrank(total: int, rank: int) -> _Vector | None:
    if rank < 0 or rank >= _exact_count(total):
        return None
    free_rank = rank
    for exclusion in _exact_exclusions(total):
        if exclusion > free_rank:
            break
        free_rank += 1
    return _free_unrank(total, free_rank)


_S6_LABEL_MAPS = tuple(
    tuple(
        _RESIDUAL_INDEX[_permuted_symbol(label, order)]
        for label in _RESIDUAL_LABELS
    )
    for order in _S6
)


def _residual_values(vector: _Vector) -> _Vector:
    result = [0] * len(_RESIDUAL_LABELS)
    for value, orbit in zip(vector, _H_ORBITS, strict=True):
        for label in orbit:
            result[_RESIDUAL_INDEX[label]] = value
    return tuple(result)


def _stabilizer_order(vector: _Vector) -> int:
    values = _residual_values(vector)
    return sum(
        tuple(values[mapping[index]] for index in range(len(values))) == values
        for mapping in _S6_LABEL_MAPS
    )


def _pair_rank(pair: _Pair) -> int | None:
    first, second = pair
    if first < 0 or second < 0:
        return None
    return first


def _pair_unrank(total: int, rank: int) -> _Pair | None:
    if rank < 0 or rank > total:
        return None
    return rank, total - rank


def _class_count(total: int) -> int:
    return sum(
        (vertex_mass + 1) * _exact_count(total - _ARITY * vertex_mass)
        for vertex_mass in range(total // _ARITY + 1)
    )


def _rank(total: int, state: _State) -> int | None:
    vertex, residual = state
    vertex_rank = _pair_rank(vertex)
    vertex_mass = sum(vertex)
    residual_mass = total - _ARITY * vertex_mass
    if (
        vertex_rank is None
        or residual_mass < 0
        or _vector_mass(residual) != residual_mass
    ):
        return None
    residual_rank = _exact_rank(residual)
    if residual_rank is None:
        return None
    prefix = sum(
        (candidate_mass + 1) * _exact_count(total - _ARITY * candidate_mass)
        for candidate_mass in range(vertex_mass)
    )
    return prefix + vertex_rank * _exact_count(residual_mass) + residual_rank


def _unrank(total: int, rank: int) -> _State | None:
    if rank < 0 or rank >= _class_count(total):
        return None
    for vertex_mass in range(total // _ARITY + 1):
        residual_mass = total - _ARITY * vertex_mass
        residual_count = _exact_count(residual_mass)
        block_count = (vertex_mass + 1) * residual_count
        if rank >= block_count:
            rank -= block_count
            continue
        vertex_rank, residual_rank = divmod(rank, residual_count)
        vertex = _pair_unrank(vertex_mass, vertex_rank)
        residual = _exact_unrank(residual_mass, residual_rank)
        assert vertex is not None
        assert residual is not None
        return vertex, residual
    raise AssertionError


def _sample_ranks(count: int) -> tuple[int, ...]:
    return tuple(sorted({0, count // 4, count // 2, 3 * count // 4, count - 1}))


def test_double_transposition_normalizer_geometry_is_exact() -> None:
    """H has quotient order eight, sixteen subgroups, and eleven rank blocks."""
    orbit_sizes = {
        size: sum(len(orbit) == size for orbit in _H_ORBITS) for size in (1, 2)
    }
    assert len(_NORMALIZER) == _NORMALIZER_ORDER
    assert len(_ACTIONS) == _QUOTIENT_ORDER
    assert len(_all_q_subgroups()) == _EXPECTED_QUOTIENT_SUBGROUPS
    assert orbit_sizes == _EXPECTED_H_ORBIT_SIZES
    assert _BLOCK_SIZES == _EXPECTED_BLOCK_SIZES
    assert _BLOCK_WEIGHTS == _EXPECTED_BLOCK_WEIGHTS


def test_double_transposition_free_rank_matches_reviewed_counts() -> None:
    """Trivial quotient stabilizers give the reviewed free sequence."""
    observed = tuple(_free_count(total) for total in range(_MAXIMUM_MASS + 1))
    assert observed == _EXPECTED_FREE_COUNTS
    for total in range(_EXHAUSTIVE_MASS + 1):
        for rank in range(_free_count(total)):
            vector = _free_unrank(total, rank)
            assert vector is not None
            assert _free_rank(vector) == rank


def test_double_transposition_exclusions_are_exact_s3_and_d10() -> None:
    """All nonnormalizing free exceptions are exact S3 or D10 extensions."""
    assert len(_S3_GROUPS) == _EXPECTED_EXCEPTION_GROUPS
    assert len(_D10_GROUPS) == _EXPECTED_EXCEPTION_GROUPS
    observed_s3: list[int] = []
    observed_d10: list[int] = []
    for total in range(_MAXIMUM_MASS + 1):
        s3, d10 = _exception_rank_sets(total)
        assert not set(s3) & set(d10)
        observed_s3.append(len(s3))
        observed_d10.append(len(d10))
    assert tuple(observed_s3) == _EXPECTED_S3_EXCEPTIONS
    assert tuple(observed_d10) == _EXPECTED_D10_EXCEPTIONS


def test_double_transposition_exact_rank_roundtrips_through_fourteen() -> None:
    """Sparse exclusion gives one dense exact-H residual interval."""
    observed = tuple(_exact_count(total) for total in range(_MAXIMUM_MASS + 1))
    assert observed == _EXPECTED_EXACT_COUNTS
    for total, count in enumerate(observed):
        assert _exact_unrank(total, -1) is None
        assert _exact_unrank(total, count) is None
        if count == 0:
            continue
        ranks = (
            range(count) if total <= _EXHAUSTIVE_MASS else _sample_ranks(count)
        )
        for rank in ranks:
            vector = _exact_unrank(total, rank)
            assert vector is not None
            assert _exact_rank(vector) == rank


def test_double_transposition_exact_samples_have_stabilizer_two() -> None:
    """Sampled retained representatives have exact S6 stabilizer H."""
    for total in range(3, _MAXIMUM_MASS + 1):
        count = _exact_count(total)
        for rank in _sample_ranks(count):
            vector = _exact_unrank(total, rank)
            assert vector is not None
            assert _stabilizer_order(vector) == _H_ORDER


def test_double_transposition_complete_rank_roundtrips_through_fourteen() -> (
    None
):
    """Repeated-six vertex prefixes form one complete exact-H interval."""
    observed = tuple(_class_count(total) for total in range(_MAXIMUM_MASS + 1))
    assert observed == _EXPECTED_COMPLETE_COUNTS
    for total, count in enumerate(observed):
        assert _unrank(total, -1) is None
        assert _unrank(total, count) is None
        if count == 0:
            continue
        for rank in _sample_ranks(count):
            state = _unrank(total, rank)
            assert state is not None
            assert _rank(total, state) == rank
