# Copyright:
#   - Copyright © 2026 Alberto Villa Osorno.
# SPDX-License-Identifier:
#   - MIT
# Confidential:
#   - false
# License-File:
#   - LICENSE-MIT
#
# Boundary-Contract:
# - Owns:
#   - Dense normalizer-free and exact ranking for the single-transposition
#     stabilizer in the top-level all-equal S6 stratum.
# - Must-Not:
#   - Materialize the million-entry S3 exclusion-rank set.
# - Allows:
#   - Inputs: H-fixed residual assignments for H generated by transposition 01.
#   - Outputs: free N(H)/H ranks, exact-H ranks, and complete outer ranks.
#   - Side effects: none.
# - Split-When:
#   - Exact S3 exception ranking requires an independently reusable primitive.
# - Merge-When:
#   - Complete dense full-S6 ranking owns every exact stabilizer stratum.
# - Summary:
#   - Rank H-fixed assignments freely, then remove S3 extensions by frontier DP.
# - Description:
#   - An optimal block order leaves at most three live S3 equalities.
# - Usage:
#   - Constructive rank for the dominant proper symmetric S6 stabilizer type.
# - Defaults:
#   - Exact residual and complete rank/unrank reach total mass fourteen.
#

"""Dense exact rank for the full-S6 single-transposition stabilizer stratum."""

from __future__ import annotations

from collections import deque
from functools import cache
from itertools import permutations
from math import comb
from typing import cast

_ARITY = 6
_EXTERNAL_ARITY = 4
_MAXIMUM_MASS = 14
_EXHAUSTIVE_MASS = 5
_EXPECTED_S4_SUBGROUPS = 30
_EXPECTED_H_ORBIT_SIZES = {1: 24, 2: 14}
_EXPECTED_BLOCK_SIZES = (4, 6, 6, 6, 4, 4, 4, 4)
_EXPECTED_FREE_COUNTS = (
    0,
    0,
    1,
    34,
    431,
    3_584,
    23_151,
    125_700,
    599_644,
    2_583_332,
    10_236_354,
    37_793_678,
    131_270_971,
    432_112_216,
    1_355_933_156,
)
_EXPECTED_EXACT_COUNTS = (
    0,
    0,
    0,
    24,
    377,
    3_356,
    22_352,
    123_220,
    592_648,
    2_565_032,
    10_191_319,
    37_688_418,
    131_035_614,
    431_605_710,
    1_354_879_279,
)
_EXPECTED_S3_EXCEPTIONS = (
    0,
    0,
    1,
    10,
    54,
    228,
    799,
    2_480,
    6_996,
    18_300,
    45_035,
    105_260,
    235_357,
    506_506,
    1_053_877,
)

_EXACT_BLOCK_ORDER = (1, 6, 0, 7, 2, 4, 3, 5)
_EXPECTED_FRONTIER_WIDTHS = (0, 3, 1, 1, 3, 0, 3, 3, 0)
_EXPECTED_COMPLETE_COUNTS = (
    0,
    0,
    0,
    24,
    377,
    3_356,
    22_352,
    123_220,
    592_648,
    2_565_080,
    10_192_073,
    37_695_130,
    131_080_318,
    431_852_150,
    1_356_064_575,
)
_S3_ORDER = 6
_S4_ORDER = 24
_INVALID_WITNESS_STATE = (-1,)
_EMPTY_WITNESS_STATE: tuple[int, ...] = ()


type _Pair = tuple[int, int]
type _PermutationSix = tuple[int, int, int, int, int, int]
type _PermutationFour = tuple[int, int, int, int]
type _HOrbit = tuple[int, ...]
type _Block = tuple[int, ...]
type _Blocks = tuple[_Block, ...]
type _Vector = tuple[int, ...]
type _LocalClass = tuple[_Block, int]
type _MassContext = tuple[int, int]
type _UnrankContext = tuple[int, int, int]
type _WitnessState = tuple[int, ...]
type _ExceptionState = tuple[_WitnessState, ...]
type _ExactState = tuple[_Pair, _Vector]
type _WitnessCountContext = tuple[int, int, int]
type _ExactSuffixContext = tuple[int, int, int]
type _ExactBlockContext = tuple[int, int, int, int]
type _RankStepContext = tuple[int, int, int]
type _UnrankStepContext = tuple[int, int, int]

_IDENTITY_SIX: _PermutationSix = (0, 1, 2, 3, 4, 5)
_TRANSPOSITION: _PermutationSix = (1, 0, 2, 3, 4, 5)
_H = (_IDENTITY_SIX, _TRANSPOSITION)
_Q4 = cast("tuple[_PermutationFour, ...]", tuple(permutations(range(4))))
_Q4_INDEX = {order: index for index, order in enumerate(_Q4)}
_IDENTITY_ELEMENT = _Q4_INDEX[0, 1, 2, 3]
_IDENTITY_GROUP = 1 << _IDENTITY_ELEMENT
_ALL_GROUP = (1 << len(_Q4)) - 1
_Q6 = cast(
    "tuple[_PermutationSix, ...]",
    tuple((0, 1, *(value + 2 for value in order)) for order in _Q4),
)
_RESIDUAL_LABELS = tuple(
    symbol
    for symbol in range(1 << _ARITY)
    if symbol.bit_count() not in {1, _ARITY - 1}
)


def _permuted_symbol(symbol: int, order: _PermutationSix) -> int:
    bits = tuple(
        (symbol >> (_ARITY - endpoint - 1)) & 1 for endpoint in range(_ARITY)
    )
    result = 0
    for source in order:
        result = (result << 1) | bits[source]
    return result


def _h_orbits() -> tuple[_HOrbit, ...]:
    unseen = set(_RESIDUAL_LABELS)
    result: list[_HOrbit] = []
    while unseen:
        seed = min(unseen)
        orbit = tuple(sorted({_permuted_symbol(seed, order) for order in _H}))
        unseen -= set(orbit)
        result.append(orbit)
    return tuple(sorted(result, key=lambda orbit: (len(orbit), orbit)))


_H_ORBITS = _h_orbits()
_H_ORBIT_INDEX = {orbit: index for index, orbit in enumerate(_H_ORBITS)}


def _image_h_orbit(orbit: _HOrbit, order: _PermutationSix) -> _HOrbit:
    return tuple(sorted(_permuted_symbol(symbol, order) for symbol in orbit))


_Q_MAPS = tuple(
    tuple(_H_ORBIT_INDEX[_image_h_orbit(orbit, order)] for orbit in _H_ORBITS)
    for order in _Q6
)


def _q_blocks() -> tuple[tuple[int, ...], ...]:
    unseen = set(range(len(_H_ORBITS)))
    fixed: list[tuple[int, ...]] = []
    moving: list[tuple[int, ...]] = []
    while unseen:
        seed = min(unseen)
        orbit = tuple(sorted({_Q_MAPS[element][seed] for element in range(24)}))
        unseen -= set(orbit)
        if len(orbit) == 1:
            fixed.append(orbit)
        else:
            moving.append(orbit)
    fixed_block = tuple(item[0] for item in fixed)
    moving.sort(
        key=lambda block: (-len(block), len(_H_ORBITS[block[0]]), block)
    )
    return (fixed_block, *moving)


_BLOCK_LABELS = _q_blocks()
_BLOCK_SIZES = tuple(len(block) for block in _BLOCK_LABELS)
_BLOCK_WEIGHTS = tuple(len(_H_ORBITS[block[0]]) for block in _BLOCK_LABELS)
_BLOCK_COUNT = len(_BLOCK_LABELS)


def _compose_four(left: int, right: int) -> int:
    return _Q4_INDEX[
        cast(
            "_PermutationFour",
            tuple(_Q4[left][_Q4[right][index]] for index in range(4)),
        )
    ]


_MULTIPLICATION = tuple(
    tuple(_compose_four(left, right) for right in range(24))
    for left in range(24)
)


def _group_elements(group: int) -> tuple[int, ...]:
    return tuple(element for element in range(24) if group & (1 << element))


def _generator_products(
    left: int, generators: tuple[int, ...]
) -> tuple[int, ...]:
    return tuple(
        product
        for right in generators
        for product in (
            _MULTIPLICATION[left][right],
            _MULTIPLICATION[right][left],
        )
    )


@cache
def _generated(generators: tuple[int, ...]) -> int:
    subgroup = {_IDENTITY_ELEMENT}
    frontier = deque([_IDENTITY_ELEMENT])
    generators = tuple(sorted(set(generators)))
    while frontier:
        left = frontier.popleft()
        for product in _generator_products(left, generators):
            if product not in subgroup:
                subgroup.add(product)
                frontier.append(product)
    return sum(1 << element for element in subgroup)


def _minimal_generators(group: int) -> tuple[int, ...]:
    generators: list[int] = []
    generated = _IDENTITY_GROUP
    for element in _group_elements(group):
        if generated & (1 << element):
            continue
        generators.append(element)
        generated = _generated(tuple(generators))
    return tuple(generators)


def _group_extensions(group: int) -> tuple[int, ...]:
    generators = _minimal_generators(group)
    return tuple(
        _generated((*generators, element))
        for element in range(24)
        if not group & (1 << element)
    )


@cache
def _all_subgroups() -> tuple[int, ...]:
    known = {_IDENTITY_GROUP}
    frontier = [_IDENTITY_GROUP]
    while frontier:
        group = frontier.pop()
        for candidate in _group_extensions(group):
            if candidate not in known:
                known.add(candidate)
                frontier.append(candidate)
    return tuple(sorted(known, key=lambda group: (-group.bit_count(), group)))


def _subgroups_of(group: int) -> tuple[int, ...]:
    return tuple(
        candidate for candidate in _all_subgroups() if candidate & ~group == 0
    )


@cache
def _block_mapping(block: int, element: int) -> tuple[int, ...]:
    labels = _BLOCK_LABELS[block]
    index = {label: position for position, label in enumerate(labels)}
    return tuple(index[_Q_MAPS[element][label]] for label in labels)


def _apply_block(vector: _Block, block: int, element: int) -> _Block:
    mapping = _block_mapping(block, element)
    result = [0] * len(vector)
    for source, destination in enumerate(mapping):
        result[destination] = vector[source]
    return tuple(result)


def _composition_count(total: int, parts: int) -> int:
    if total < 0 or parts <= 0:
        return 0
    return comb(total + parts - 1, parts - 1)


@cache
def _compositions(total: int, parts: int) -> tuple[_Block, ...]:
    if parts == 1:
        return ((total,),)
    return tuple(
        (first, *suffix)
        for first in range(total + 1)
        for suffix in _compositions(total - first, parts - 1)
    )


def _composition_rank(vector: _Block) -> int | None:
    if not vector or any(value < 0 for value in vector):
        return None
    remaining = sum(vector)
    rank = 0
    for index, value in enumerate(vector[:-1]):
        tail = len(vector) - index - 1
        rank += sum(
            _composition_count(remaining - earlier, tail)
            for earlier in range(value)
        )
        remaining -= value
    return rank


def _composition_unrank(total: int, parts: int, rank: int) -> _Block | None:
    if rank < 0 or rank >= _composition_count(total, parts):
        return None
    remaining = total
    residual_rank = rank
    result: list[int] = []
    for index in range(parts - 1):
        tail = parts - index - 1
        for value in range(remaining + 1):
            count = _composition_count(remaining - value, tail)
            if residual_rank >= count:
                residual_rank -= count
                continue
            result.append(value)
            remaining -= value
            break
    result.append(remaining)
    return tuple(result)


def _stabilizer(vector: _Block, block: int, group: int) -> int:
    return sum(
        1 << element
        for element in _group_elements(group)
        if _apply_block(vector, block, element) == vector
    )


@cache
def _local_classes(
    block: int, mass: int, group: int
) -> tuple[_LocalClass, ...]:
    weight = _BLOCK_WEIGHTS[block]
    if mass % weight != 0:
        return ()
    scalar_mass = mass // weight
    if group == _IDENTITY_GROUP:
        return tuple(
            (vector, _IDENTITY_GROUP)
            for vector in _compositions(scalar_mass, _BLOCK_SIZES[block])
        )
    elements = _group_elements(group)
    result: list[_LocalClass] = []
    for vector in _compositions(scalar_mass, _BLOCK_SIZES[block]):
        representative = min(
            _apply_block(vector, block, item) for item in elements
        )
        if vector == representative:
            result.append((vector, _stabilizer(vector, block, group)))
    return tuple(result)


def _fixed_count(total: int, cycles: tuple[int, ...]) -> int:
    coefficients = [1] + [0] * total
    for cycle in cycles:
        next_coefficients = [0] * (total + 1)
        for degree, coefficient in enumerate(coefficients):
            if coefficient == 0:
                continue
            for addition in range(0, total - degree + 1, cycle):
                next_coefficients[degree + addition] += coefficient
        coefficients = next_coefficients
    return coefficients[total]


@cache
def _remaining_group_weights(block: int, group: int) -> tuple[int, ...]:
    elements = _group_elements(group)
    result: list[int] = []
    for candidate in range(block, _BLOCK_COUNT):
        unseen = set(range(_BLOCK_SIZES[candidate]))
        while unseen:
            seed = min(unseen)
            orbit = {
                _block_mapping(candidate, element)[seed] for element in elements
            }
            unseen -= orbit
            result.append(len(orbit) * _BLOCK_WEIGHTS[candidate])
    return tuple(sorted(result))


@cache
def _free_suffix_count(block: int, total: int, group: int) -> int:
    if block == _BLOCK_COUNT:
        return int(total == 0 and group == _IDENTITY_GROUP)
    exact: dict[int, int] = {}
    for subgroup in _subgroups_of(group):
        fixed = _fixed_count(total, _remaining_group_weights(block, subgroup))
        for larger, value in exact.items():
            is_larger = larger.bit_count() > subgroup.bit_count()
            is_container = subgroup & ~larger == 0
            if is_larger and is_container:
                fixed -= value
        assert fixed >= 0
        exact[subgroup] = fixed
    trivial_assignments = exact[_IDENTITY_GROUP]
    assert trivial_assignments % group.bit_count() == 0
    return trivial_assignments // group.bit_count()


def _block_mass_count(block: int, mass: int, context: _MassContext) -> int:
    suffix_mass, group = context
    if block == 0 or group == _IDENTITY_GROUP:
        weight = _BLOCK_WEIGHTS[block]
        if mass % weight != 0:
            return 0
        local = _composition_count(mass // weight, _BLOCK_SIZES[block])
        return local * _free_suffix_count(block + 1, suffix_mass, group)
    return sum(
        _free_suffix_count(block + 1, suffix_mass, stabilizer)
        for _, stabilizer in _local_classes(block, mass, group)
    )


def _canonicalize_block(
    blocks: list[_Block], block: int, group: int
) -> tuple[_Block, int]:
    candidates = tuple(
        (_apply_block(blocks[block], block, element), element)
        for element in _group_elements(group)
    )
    representative, chosen = min(candidates)
    for index in range(block, _BLOCK_COUNT):
        blocks[index] = _apply_block(blocks[index], index, chosen)
    return representative, _stabilizer(representative, block, group)


def _block_mass(vector: _Block, block: int) -> int:
    return sum(vector) * _BLOCK_WEIGHTS[block]


def _rank_local_block(
    blocks: list[_Block], block: int, context: _MassContext
) -> tuple[int, int] | None:
    suffix_mass, group = context
    vector = blocks[block]
    if block == 0 or group == _IDENTITY_GROUP:
        local_rank = _composition_rank(vector)
        assert local_rank is not None
        suffix = _free_suffix_count(block + 1, suffix_mass, group)
        if suffix == 0:
            return None
        return local_rank * suffix, group
    representative, stabilizer = _canonicalize_block(blocks, block, group)
    result = 0
    for candidate, candidate_stabilizer in _local_classes(
        block, _block_mass(representative, block), group
    ):
        count = _free_suffix_count(block + 1, suffix_mass, candidate_stabilizer)
        if candidate == representative:
            return None if count == 0 else (result, stabilizer)
        result += count
    raise AssertionError


def _extract_blocks(vector: _Vector) -> _Blocks | None:
    if len(vector) != len(_H_ORBITS) or any(value < 0 for value in vector):
        return None
    return tuple(
        tuple(vector[index] for index in labels) for labels in _BLOCK_LABELS
    )


def _build_vector(blocks: _Blocks) -> _Vector:
    result = [0] * len(_H_ORBITS)
    for labels, block in zip(_BLOCK_LABELS, blocks, strict=True):
        for label, value in zip(labels, block, strict=True):
            result[label] = value
    return tuple(result)


def _vector_mass(vector: _Vector) -> int:
    return sum(
        value * len(orbit)
        for value, orbit in zip(vector, _H_ORBITS, strict=True)
    )


def _free_count(total: int) -> int:
    return _free_suffix_count(0, total, _ALL_GROUP)


def _free_rank(vector: _Vector) -> int | None:
    extracted = _extract_blocks(vector)
    if extracted is None:
        return None
    blocks = list(extracted)
    remaining_mass = _vector_mass(vector)
    group = _ALL_GROUP
    rank = 0
    for block in range(_BLOCK_COUNT):
        mass = _block_mass(blocks[block], block)
        rank += sum(
            _block_mass_count(
                block, candidate, (remaining_mass - candidate, group)
            )
            for candidate in range(mass)
        )
        local = _rank_local_block(blocks, block, (remaining_mass - mass, group))
        if local is None:
            return None
        local_rank, group = local
        rank += local_rank
        remaining_mass -= mass
    return rank if group == _IDENTITY_GROUP else None


def _unrank_local_block(
    block: int, mass: int, context: _UnrankContext
) -> tuple[_Block, int, int]:
    suffix_mass, group, rank = context
    if block == 0 or group == _IDENTITY_GROUP:
        suffix = _free_suffix_count(block + 1, suffix_mass, group)
        assert suffix > 0
        local_rank, residual = divmod(rank, suffix)
        weight = _BLOCK_WEIGHTS[block]
        assert mass % weight == 0
        vector = _composition_unrank(
            mass // weight, _BLOCK_SIZES[block], local_rank
        )
        assert vector is not None
        return vector, group, residual
    for vector, stabilizer in _local_classes(block, mass, group):
        count = _free_suffix_count(block + 1, suffix_mass, stabilizer)
        if rank >= count:
            rank -= count
            continue
        return vector, stabilizer, rank
    raise AssertionError


def _free_unrank(total: int, rank: int) -> _Vector | None:
    if rank < 0 or rank >= _free_count(total):
        return None
    blocks: list[_Block] = []
    remaining_mass = total
    group = _ALL_GROUP
    for block in range(_BLOCK_COUNT):
        for mass in range(remaining_mass + 1):
            count = _block_mass_count(
                block, mass, (remaining_mass - mass, group)
            )
            if rank >= count:
                rank -= count
                continue
            vector, group, rank = _unrank_local_block(
                block,
                mass,
                (remaining_mass - mass, group, rank),
            )
            blocks.append(vector)
            remaining_mass -= mass
            break
    assert remaining_mass == 0
    assert rank == 0
    assert group == _IDENTITY_GROUP
    return _build_vector(tuple(blocks))


def _compose_six(
    left: _PermutationSix, right: _PermutationSix
) -> _PermutationSix:
    return cast(
        "_PermutationSix",
        tuple(left[right[index]] for index in range(_ARITY)),
    )


def _swap_six(first: int, second: int) -> _PermutationSix:
    order = list(range(_ARITY))
    order[first], order[second] = order[second], order[first]
    return cast("_PermutationSix", tuple(order))


def _six_products(
    left: _PermutationSix, generators: tuple[_PermutationSix, ...]
) -> tuple[_PermutationSix, ...]:
    return tuple(
        product
        for right in generators
        for product in (_compose_six(left, right), _compose_six(right, left))
    )


def _generated_six(
    generators: tuple[_PermutationSix, ...],
) -> tuple[_PermutationSix, ...]:
    subgroup = {_IDENTITY_SIX}
    frontier = deque([_IDENTITY_SIX])
    while frontier:
        left = frontier.popleft()
        for product in _six_products(left, generators):
            if product not in subgroup:
                subgroup.add(product)
                frontier.append(product)
    return tuple(sorted(subgroup))


_S3_WITNESSES = tuple(
    _generated_six((_TRANSPOSITION, _swap_six(0, endpoint)))
    for endpoint in range(2, _ARITY)
)
_H_LABEL_INDEX = {
    label: index for index, orbit in enumerate(_H_ORBITS) for label in orbit
}
_EXACT_COORDINATE_STEP = {
    coordinate: step
    for step, block in enumerate(_EXACT_BLOCK_ORDER)
    for coordinate in _BLOCK_LABELS[block]
}


@cache
def _witness_classes(witness: int) -> tuple[tuple[int, ...], ...]:
    unseen = set(range(len(_H_ORBITS)))
    result: list[tuple[int, ...]] = []
    while unseen:
        seed = min(unseen)
        labels = set(_H_ORBITS[seed])
        orbit_labels = {
            _permuted_symbol(label, element)
            for label in labels
            for element in _S3_WITNESSES[witness]
        }
        coordinates = tuple(
            sorted(_H_LABEL_INDEX[label] for label in orbit_labels)
        )
        unseen -= set(coordinates)
        result.append(coordinates)
    return tuple(result)


@cache
def _crossing_witness_classes(
    witness: int, step: int
) -> tuple[tuple[int, ...], ...]:
    return tuple(
        coordinates
        for coordinates in _witness_classes(witness)
        if any(_EXACT_COORDINATE_STEP[item] < step for item in coordinates)
        and any(_EXACT_COORDINATE_STEP[item] >= step for item in coordinates)
    )


@cache
def _suffix_witness_classes(
    witness: int, step: int
) -> tuple[tuple[int, ...], ...]:
    return tuple(
        coordinates
        for coordinates in _witness_classes(witness)
        if all(_EXACT_COORDINATE_STEP[item] >= step for item in coordinates)
    )


def _prefix_values(blocks: tuple[_Block, ...]) -> dict[int, int]:
    return {
        coordinate: value
        for step, vector in enumerate(blocks)
        for coordinate, value in zip(
            _BLOCK_LABELS[_EXACT_BLOCK_ORDER[step]], vector, strict=True
        )
    }


def _witness_state(
    witness: int, step: int, known: dict[int, int]
) -> _WitnessState:
    for coordinates in _witness_classes(witness):
        values = {known[item] for item in coordinates if item in known}
        if len(values) > 1:
            return _INVALID_WITNESS_STATE
    result: list[int] = []
    for coordinates in _crossing_witness_classes(witness, step):
        values = {known[item] for item in coordinates if item in known}
        assert len(values) == 1
        result.append(next(iter(values)))
    return tuple(result)


def _exception_state(step: int, blocks: tuple[_Block, ...]) -> _ExceptionState:
    known = _prefix_values(blocks)
    return tuple(
        _witness_state(witness, step, known)
        for witness in range(len(_S3_WITNESSES))
    )


@cache
def _exact_remaining_group_weights(step: int, group: int) -> tuple[int, ...]:
    elements = _group_elements(group)
    result: list[int] = []
    for position in range(step, _BLOCK_COUNT):
        block = _EXACT_BLOCK_ORDER[position]
        unseen = set(range(_BLOCK_SIZES[block]))
        while unseen:
            seed = min(unseen)
            orbit = {
                _block_mapping(block, element)[seed] for element in elements
            }
            unseen -= orbit
            result.append(len(orbit) * _BLOCK_WEIGHTS[block])
    return tuple(sorted(result))


@cache
def _exact_free_suffix_count(step: int, total: int, group: int) -> int:
    if step == _BLOCK_COUNT:
        return int(total == 0 and group == _IDENTITY_GROUP)
    exact: dict[int, int] = {}
    for subgroup in _subgroups_of(group):
        fixed = _fixed_count(
            total, _exact_remaining_group_weights(step, subgroup)
        )
        for larger, value in exact.items():
            is_larger = larger.bit_count() > subgroup.bit_count()
            is_container = subgroup & ~larger == 0
            if is_larger and is_container:
                fixed -= value
        assert fixed >= 0
        exact[subgroup] = fixed
    trivial_assignments = exact[_IDENTITY_GROUP]
    assert trivial_assignments % group.bit_count() == 0
    return trivial_assignments // group.bit_count()


def _union(parent: dict[int, int], first: int, second: int) -> None:
    def root(item: int) -> int:
        while parent[item] != item:
            parent[item] = parent[parent[item]]
            item = parent[item]
        return item

    left = root(first)
    right = root(second)
    if left != right:
        parent[right] = left


def _roots(parent: dict[int, int], item: int) -> int:
    while parent[item] != item:
        parent[item] = parent[parent[item]]
        item = parent[item]
    return item


def _witness_suffix_components(
    step: int, subgroup: int, witness: int
) -> tuple[set[int], dict[int, int]]:
    suffix = {
        coordinate
        for coordinate in range(len(_H_ORBITS))
        if _EXACT_COORDINATE_STEP[coordinate] >= step
    }
    parent = {coordinate: coordinate for coordinate in suffix}
    for element in _group_elements(subgroup):
        mapping = _Q_MAPS[element]
        for coordinate in suffix:
            _union(parent, coordinate, mapping[coordinate])
    for coordinates in _suffix_witness_classes(witness, step):
        for coordinate in coordinates[1:]:
            _union(parent, coordinates[0], coordinate)
    return suffix, parent


def _crossing_fixed_values(
    context: tuple[int, int],
    state: _WitnessState,
    suffix: set[int],
    *,
    parent: dict[int, int],
) -> dict[int, int] | None:
    witness, step = context
    fixed_values: dict[int, int] = {}
    crossing = _crossing_witness_classes(witness, step)
    assert len(crossing) == len(state)
    for coordinates, value in zip(crossing, state, strict=True):
        for coordinate in coordinates:
            if coordinate not in suffix:
                continue
            root = _roots(parent, coordinate)
            previous = fixed_values.get(root)
            if previous is not None and previous != value:
                return None
            fixed_values[root] = value
    return fixed_values


def _component_weights(
    suffix: set[int], parent: dict[int, int]
) -> dict[int, int]:
    result: dict[int, int] = {}
    for coordinate in suffix:
        root = _roots(parent, coordinate)
        result[root] = result.get(root, 0) + len(_H_ORBITS[coordinate])
    return result


def _fixed_component_count(
    total: int,
    component_weights: dict[int, int],
    fixed_values: dict[int, int],
) -> int:
    forced_mass = sum(
        component_weights[root] * value for root, value in fixed_values.items()
    )
    if forced_mass > total:
        return 0
    free_weights = tuple(
        sorted(
            weight
            for root, weight in component_weights.items()
            if root not in fixed_values
        )
    )
    return _fixed_count(total - forced_mass, free_weights)


@cache
def _witness_suffix_fixed_count(
    context: _WitnessCountContext,
    witness: int,
    state: _WitnessState,
) -> int:
    if state == _INVALID_WITNESS_STATE:
        return 0
    step, total, subgroup = context
    suffix, parent = _witness_suffix_components(step, subgroup, witness)
    fixed_values = _crossing_fixed_values(
        (witness, step), state, suffix, parent=parent
    )
    if fixed_values is None:
        return 0
    return _fixed_component_count(
        total, _component_weights(suffix, parent), fixed_values
    )


@cache
def _exception_suffix_count(
    context: _ExactSuffixContext, state: _ExceptionState
) -> int:
    step, total, group = context
    exact: dict[int, int] = {}
    for subgroup in _subgroups_of(group):
        fixed = sum(
            _witness_suffix_fixed_count(
                (step, total, subgroup), witness, state[witness]
            )
            for witness in range(len(_S3_WITNESSES))
        )
        for larger, value in exact.items():
            is_larger = larger.bit_count() > subgroup.bit_count()
            is_container = subgroup & ~larger == 0
            if is_larger and is_container:
                fixed -= value
        assert fixed >= 0
        exact[subgroup] = fixed
    trivial_assignments = exact[_IDENTITY_GROUP]
    assert trivial_assignments % group.bit_count() == 0
    return trivial_assignments // group.bit_count()


@cache
def _exact_suffix_count(
    context: _ExactSuffixContext, state: _ExceptionState
) -> int:
    step, total, group = context
    result = _exact_free_suffix_count(
        step, total, group
    ) - _exception_suffix_count(context, state)
    assert result >= 0
    return result


def _exact_local_classes(
    step: int, mass: int, group: int
) -> tuple[_LocalClass, ...]:
    return _local_classes(_EXACT_BLOCK_ORDER[step], mass, group)


def _exact_block_mass(step: int, vector: _Block) -> int:
    return sum(vector) * _BLOCK_WEIGHTS[_EXACT_BLOCK_ORDER[step]]


def _exact_transform(vector: _Block, step: int, element: int) -> _Block:
    return _apply_block(vector, _EXACT_BLOCK_ORDER[step], element)


def _exact_canonicalize_block(
    blocks: list[_Block], step: int, group: int
) -> tuple[_Block, int]:
    representative, chosen = min(
        (_exact_transform(blocks[step], step, element), element)
        for element in _group_elements(group)
    )
    for position in range(step, _BLOCK_COUNT):
        blocks[position] = _exact_transform(blocks[position], position, chosen)
    stabilizer = _stabilizer(representative, _EXACT_BLOCK_ORDER[step], group)
    return representative, stabilizer


def _exact_extract_blocks(vector: _Vector) -> list[_Block] | None:
    if len(vector) != len(_H_ORBITS) or any(value < 0 for value in vector):
        return None
    return [
        tuple(vector[index] for index in _BLOCK_LABELS[block])
        for block in _EXACT_BLOCK_ORDER
    ]


def _exact_build_vector(blocks: tuple[_Block, ...]) -> _Vector:
    result = [0] * len(_H_ORBITS)
    for step, vector in enumerate(blocks):
        for coordinate, value in zip(
            _BLOCK_LABELS[_EXACT_BLOCK_ORDER[step]], vector, strict=True
        ):
            result[coordinate] = value
    return tuple(result)


def _exact_count(total: int) -> int:
    empty_state = tuple(_EMPTY_WITNESS_STATE for _ in range(len(_S3_WITNESSES)))
    return _exact_suffix_count((0, total, _ALL_GROUP), empty_state)


def _exact_block_mass_count(
    context: _ExactBlockContext, prefix: tuple[_Block, ...]
) -> int:
    step, mass, suffix_mass, group = (*context[:2], *context[2:])
    return sum(
        _exact_suffix_count(
            (step + 1, suffix_mass, stabilizer),
            _exception_state(step + 1, (*prefix, vector)),
        )
        for vector, stabilizer in _exact_local_classes(step, mass, group)
    )


def _exact_rank_step(
    blocks: list[_Block],
    step: int,
    prefix: list[_Block],
    *,
    context: _RankStepContext,
) -> tuple[int, int, int] | None:
    remaining_mass, group, rank = context
    mass = _exact_block_mass(step, blocks[step])
    rank += sum(
        _exact_block_mass_count(
            (step, candidate, remaining_mass - candidate, group), tuple(prefix)
        )
        for candidate in range(mass)
    )
    representative, stabilizer = _exact_canonicalize_block(blocks, step, group)
    for candidate, candidate_stabilizer in _exact_local_classes(
        step, mass, group
    ):
        count = _exact_suffix_count(
            (step + 1, remaining_mass - mass, candidate_stabilizer),
            _exception_state(step + 1, (*prefix, candidate)),
        )
        if candidate != representative:
            rank += count
            continue
        if count == 0:
            return None
        prefix.append(representative)
        return remaining_mass - mass, stabilizer, rank
    raise AssertionError


def _exact_rank(vector: _Vector) -> int | None:
    blocks = _exact_extract_blocks(vector)
    remaining_mass = _vector_mass(vector)
    if blocks is None or remaining_mass > _MAXIMUM_MASS:
        return None
    group = _ALL_GROUP
    prefix: list[_Block] = []
    rank = 0
    for step in range(_BLOCK_COUNT):
        context = _exact_rank_step(
            blocks, step, prefix, context=(remaining_mass, group, rank)
        )
        if context is None:
            return None
        remaining_mass, group, rank = context
    return rank if group == _IDENTITY_GROUP else None


def _choose_exact_local_class(
    step: int,
    mass: int,
    prefix: list[_Block],
    *,
    context: _UnrankStepContext,
) -> tuple[int, int] | None:
    remaining_mass, group, rank = context
    for vector, stabilizer in _exact_local_classes(step, mass, group):
        state = _exception_state(step + 1, (*prefix, vector))
        count = _exact_suffix_count(
            (step + 1, remaining_mass - mass, stabilizer), state
        )
        if rank >= count:
            rank -= count
            continue
        prefix.append(vector)
        return stabilizer, rank
    return None


def _exact_unrank_step(
    step: int,
    prefix: list[_Block],
    *,
    context: _UnrankStepContext,
) -> tuple[int, int, int]:
    remaining_mass, group, rank = context
    for mass in range(remaining_mass + 1):
        count = _exact_block_mass_count(
            (step, mass, remaining_mass - mass, group), tuple(prefix)
        )
        if rank >= count:
            rank -= count
            continue
        chosen = _choose_exact_local_class(
            step, mass, prefix, context=(remaining_mass, group, rank)
        )
        assert chosen is not None
        stabilizer, rank = chosen
        return remaining_mass - mass, stabilizer, rank
    raise AssertionError


def _exact_unrank(total: int, rank: int) -> _Vector | None:
    if rank < 0 or rank >= _exact_count(total):
        return None
    prefix: list[_Block] = []
    remaining_mass = total
    group = _ALL_GROUP
    for step in range(_BLOCK_COUNT):
        remaining_mass, group, rank = _exact_unrank_step(
            step, prefix, context=(remaining_mass, group, rank)
        )
    assert remaining_mass == 0
    assert rank == 0
    assert group == _IDENTITY_GROUP
    return _exact_build_vector(tuple(prefix))


def _pair_rank(pair: _Pair) -> int | None:
    first, second = pair
    if first < 0 or second < 0:
        return None
    return first


def _pair_unrank(total: int, rank: int) -> _Pair | None:
    if rank < 0 or rank > total:
        return None
    return rank, total - rank


def _class_count(total: int) -> int:
    return sum(
        (vertex_mass + 1) * _exact_count(total - _S3_ORDER * vertex_mass)
        for vertex_mass in range(total // _S3_ORDER + 1)
    )


def _rank(total: int, state: _ExactState) -> int | None:
    vertex, residual = state
    vertex_rank = _pair_rank(vertex)
    vertex_mass = sum(vertex)
    residual_mass = total - _S3_ORDER * vertex_mass
    invalid = (
        vertex_rank is None
        or residual_mass < 0
        or _vector_mass(residual) != residual_mass
    )
    if invalid:
        return None
    assert vertex_rank is not None
    residual_rank = _exact_rank(residual)
    if residual_rank is None:
        return None
    prefix = sum(
        (candidate_mass + 1) * _exact_count(total - _S3_ORDER * candidate_mass)
        for candidate_mass in range(vertex_mass)
    )
    return prefix + vertex_rank * _exact_count(residual_mass) + residual_rank


def _unrank(total: int, rank: int) -> _ExactState | None:
    if rank < 0 or rank >= _class_count(total):
        return None
    for vertex_mass in range(total // _S3_ORDER + 1):
        residual_mass = total - _S3_ORDER * vertex_mass
        residual_count = _exact_count(residual_mass)
        block_count = (vertex_mass + 1) * residual_count
        if rank >= block_count:
            rank -= block_count
            continue
        vertex_rank, residual_rank = divmod(rank, residual_count)
        vertex = _pair_unrank(vertex_mass, vertex_rank)
        residual = _exact_unrank(residual_mass, residual_rank)
        assert vertex is not None
        assert residual is not None
        return vertex, residual
    raise AssertionError


def test_transposition_normalizer_geometry_is_exact() -> None:
    """H has 24 singleton and 14 paired coordinates in eight S4 blocks."""
    spectrum = {
        size: sum(len(orbit) == size for orbit in _H_ORBITS) for size in (1, 2)
    }
    assert spectrum == _EXPECTED_H_ORBIT_SIZES
    assert _BLOCK_SIZES == _EXPECTED_BLOCK_SIZES
    assert _BLOCK_WEIGHTS == (1, 1, 1, 2, 1, 1, 2, 2)
    assert len(_all_subgroups()) == _EXPECTED_S4_SUBGROUPS


def test_transposition_free_counts_match_reviewed_sequence() -> None:
    """Trivial S4 suffix stabilizer counts give the reviewed free sequence."""
    observed = tuple(_free_count(total) for total in range(_MAXIMUM_MASS + 1))
    assert observed == _EXPECTED_FREE_COUNTS


def test_transposition_free_minus_exact_is_s3_sequence() -> None:
    """The only nonnormalizing free exceptions are the reviewed S3 sequence."""
    difference = tuple(
        free - exact
        for free, exact in zip(
            _EXPECTED_FREE_COUNTS, _EXPECTED_EXACT_COUNTS, strict=True
        )
    )
    assert difference == _EXPECTED_S3_EXCEPTIONS


def test_transposition_s3_witnesses_are_unique_on_free_classes() -> None:
    """Two distinct S3 witnesses force a nontrivial normalizer symmetry."""
    for first in range(len(_S3_WITNESSES)):
        for second in range(first + 1, len(_S3_WITNESSES)):
            generated = _generated_six((
                *_S3_WITNESSES[first],
                *_S3_WITNESSES[second],
            ))
            assert len(generated) == _S4_ORDER
            assert _swap_six(first + 2, second + 2) in generated


def test_transposition_exact_frontier_and_counts_are_exact() -> None:
    """The compact S3 frontier reproduces every reviewed exact-H count."""
    assert all(len(group) == _S3_ORDER for group in _S3_WITNESSES)
    observed_widths = tuple(
        len(_crossing_witness_classes(0, step))
        for step in range(_BLOCK_COUNT + 1)
    )
    assert observed_widths == _EXPECTED_FRONTIER_WIDTHS
    for witness in range(1, len(_S3_WITNESSES)):
        assert (
            tuple(
                len(_crossing_witness_classes(witness, step))
                for step in range(_BLOCK_COUNT + 1)
            )
            == _EXPECTED_FRONTIER_WIDTHS
        )
    observed = tuple(_exact_count(total) for total in range(_MAXIMUM_MASS + 1))
    assert observed == _EXPECTED_EXACT_COUNTS


def test_transposition_exact_rank_exhausts_small_domains() -> None:
    """Exact-H residual rank is a contiguous bijection through mass four."""
    for total in range(5):
        for rank in range(_exact_count(total)):
            vector = _exact_unrank(total, rank)
            assert vector is not None
            assert _exact_rank(vector) == rank


def test_transposition_exact_rank_roundtrips_through_fourteen() -> None:
    """Boundary and interior exact-H ranks invert through residual mass 14."""
    for total in range(_MAXIMUM_MASS + 1):
        count = _exact_count(total)
        assert _exact_unrank(total, -1) is None
        assert _exact_unrank(total, count) is None
        if count == 0:
            continue
        for rank in sorted({
            0,
            count // 4,
            count // 2,
            3 * count // 4,
            count - 1,
        }):
            vector = _exact_unrank(total, rank)
            assert vector is not None
            assert _exact_rank(vector) == rank


def test_transposition_complete_rank_roundtrips_through_fourteen() -> None:
    """Repeated-six vertex prefixes give one dense complete exact-H interval."""
    observed = tuple(_class_count(total) for total in range(_MAXIMUM_MASS + 1))
    assert observed == _EXPECTED_COMPLETE_COUNTS
    for total, count in enumerate(observed):
        assert _unrank(total, -1) is None
        assert _unrank(total, count) is None
        if count == 0:
            continue
        for rank in sorted({
            0,
            count // 4,
            count // 2,
            3 * count // 4,
            count - 1,
        }):
            state = _unrank(total, rank)
            assert state is not None
            assert _rank(total, state) == rank


def test_transposition_free_rank_exhausts_small_domains() -> None:
    """Free normalizer rank is a contiguous bijection through mass five."""
    for total in range(_EXHAUSTIVE_MASS + 1):
        for rank in range(_free_count(total)):
            vector = _free_unrank(total, rank)
            assert vector is not None
            assert _free_rank(vector) == rank


def test_transposition_free_rank_roundtrips_through_fourteen() -> None:
    """Boundary and interior free ranks roundtrip through residual mass 14."""
    for total in range(_MAXIMUM_MASS + 1):
        count = _free_count(total)
        assert _free_unrank(total, -1) is None
        assert _free_unrank(total, count) is None
        if count == 0:
            continue
        for rank in sorted({
            0,
            count // 4,
            count // 2,
            3 * count // 4,
            count - 1,
        }):
            vector = _free_unrank(total, rank)
            assert vector is not None
            assert _free_rank(vector) == rank
