# Copyright:
#   - Copyright © 2026 Alberto Villa Osorno.
# SPDX-License-Identifier:
#   - MIT
# Confidential:
#   - false
# License-File:
#   - LICENSE-MIT
#
# Boundary-Contract:
# - Owns:
#   - Dense normalizer-free ranking and exact-count decomposition for the
#     single-transposition stabilizer in the top-level all-equal S6 stratum.
# - Must-Not:
#   - Claim exact-transposition dense rank until the S3 exceptions are removed.
# - Allows:
#   - Inputs: H-fixed residual assignments for H generated by transposition 01.
#   - Outputs: free N(H)/H ranks and exact-H/S3 exception count identities.
#   - Side effects: none.
# - Split-When:
#   - Exact S3 exception ranking requires an independently reusable primitive.
# - Merge-When:
#   - Complete dense full-S6 ranking owns every exact stabilizer stratum.
# - Summary:
#   - Rank H-fixed assignments freely under the S4 normalizer quotient.
# - Description:
#   - Möbius inversion over the 30 S4 subgroups counts free suffixes directly.
# - Usage:
#   - Scalable prerequisite for the dominant proper symmetric S6 stratum.
# - Defaults:
#   - Free rank/unrank and exact-count identities reach residual mass fourteen.
#

"""Free normalizer rank for the full-S6 single-transposition stratum."""

from __future__ import annotations

from collections import deque
from functools import cache
from itertools import permutations
from math import comb
from typing import cast

_ARITY = 6
_EXTERNAL_ARITY = 4
_MAXIMUM_MASS = 14
_EXHAUSTIVE_MASS = 5
_EXPECTED_S4_SUBGROUPS = 30
_EXPECTED_H_ORBIT_SIZES = {1: 24, 2: 14}
_EXPECTED_BLOCK_SIZES = (4, 6, 6, 6, 4, 4, 4, 4)
_EXPECTED_FREE_COUNTS = (
    0,
    0,
    1,
    34,
    431,
    3_584,
    23_151,
    125_700,
    599_644,
    2_583_332,
    10_236_354,
    37_793_678,
    131_270_971,
    432_112_216,
    1_355_933_156,
)
_EXPECTED_EXACT_COUNTS = (
    0,
    0,
    0,
    24,
    377,
    3_356,
    22_352,
    123_220,
    592_648,
    2_565_032,
    10_191_319,
    37_688_418,
    131_035_614,
    431_605_710,
    1_354_879_279,
)
_EXPECTED_S3_EXCEPTIONS = (
    0,
    0,
    1,
    10,
    54,
    228,
    799,
    2_480,
    6_996,
    18_300,
    45_035,
    105_260,
    235_357,
    506_506,
    1_053_877,
)


type _PermutationSix = tuple[int, int, int, int, int, int]
type _PermutationFour = tuple[int, int, int, int]
type _HOrbit = tuple[int, ...]
type _Block = tuple[int, ...]
type _Blocks = tuple[_Block, ...]
type _Vector = tuple[int, ...]
type _LocalClass = tuple[_Block, int]
type _MassContext = tuple[int, int]
type _UnrankContext = tuple[int, int, int]

_IDENTITY_SIX: _PermutationSix = (0, 1, 2, 3, 4, 5)
_TRANSPOSITION: _PermutationSix = (1, 0, 2, 3, 4, 5)
_H = (_IDENTITY_SIX, _TRANSPOSITION)
_Q4 = cast("tuple[_PermutationFour, ...]", tuple(permutations(range(4))))
_Q4_INDEX = {order: index for index, order in enumerate(_Q4)}
_IDENTITY_ELEMENT = _Q4_INDEX[0, 1, 2, 3]
_IDENTITY_GROUP = 1 << _IDENTITY_ELEMENT
_ALL_GROUP = (1 << len(_Q4)) - 1
_Q6 = cast(
    "tuple[_PermutationSix, ...]",
    tuple((0, 1, *(value + 2 for value in order)) for order in _Q4),
)
_RESIDUAL_LABELS = tuple(
    symbol
    for symbol in range(1 << _ARITY)
    if symbol.bit_count() not in {1, _ARITY - 1}
)


def _permuted_symbol(symbol: int, order: _PermutationSix) -> int:
    bits = tuple(
        (symbol >> (_ARITY - endpoint - 1)) & 1 for endpoint in range(_ARITY)
    )
    result = 0
    for source in order:
        result = (result << 1) | bits[source]
    return result


def _h_orbits() -> tuple[_HOrbit, ...]:
    unseen = set(_RESIDUAL_LABELS)
    result: list[_HOrbit] = []
    while unseen:
        seed = min(unseen)
        orbit = tuple(sorted({_permuted_symbol(seed, order) for order in _H}))
        unseen -= set(orbit)
        result.append(orbit)
    return tuple(sorted(result, key=lambda orbit: (len(orbit), orbit)))


_H_ORBITS = _h_orbits()
_H_ORBIT_INDEX = {orbit: index for index, orbit in enumerate(_H_ORBITS)}


def _image_h_orbit(orbit: _HOrbit, order: _PermutationSix) -> _HOrbit:
    return tuple(sorted(_permuted_symbol(symbol, order) for symbol in orbit))


_Q_MAPS = tuple(
    tuple(_H_ORBIT_INDEX[_image_h_orbit(orbit, order)] for orbit in _H_ORBITS)
    for order in _Q6
)


def _q_blocks() -> tuple[tuple[int, ...], ...]:
    unseen = set(range(len(_H_ORBITS)))
    fixed: list[tuple[int, ...]] = []
    moving: list[tuple[int, ...]] = []
    while unseen:
        seed = min(unseen)
        orbit = tuple(sorted({_Q_MAPS[element][seed] for element in range(24)}))
        unseen -= set(orbit)
        if len(orbit) == 1:
            fixed.append(orbit)
        else:
            moving.append(orbit)
    fixed_block = tuple(item[0] for item in fixed)
    moving.sort(
        key=lambda block: (-len(block), len(_H_ORBITS[block[0]]), block)
    )
    return (fixed_block, *moving)


_BLOCK_LABELS = _q_blocks()
_BLOCK_SIZES = tuple(len(block) for block in _BLOCK_LABELS)
_BLOCK_WEIGHTS = tuple(len(_H_ORBITS[block[0]]) for block in _BLOCK_LABELS)
_BLOCK_COUNT = len(_BLOCK_LABELS)


def _compose_four(left: int, right: int) -> int:
    return _Q4_INDEX[
        cast(
            "_PermutationFour",
            tuple(_Q4[left][_Q4[right][index]] for index in range(4)),
        )
    ]


_MULTIPLICATION = tuple(
    tuple(_compose_four(left, right) for right in range(24))
    for left in range(24)
)


def _group_elements(group: int) -> tuple[int, ...]:
    return tuple(element for element in range(24) if group & (1 << element))


def _generator_products(
    left: int, generators: tuple[int, ...]
) -> tuple[int, ...]:
    return tuple(
        product
        for right in generators
        for product in (
            _MULTIPLICATION[left][right],
            _MULTIPLICATION[right][left],
        )
    )


@cache
def _generated(generators: tuple[int, ...]) -> int:
    subgroup = {_IDENTITY_ELEMENT}
    frontier = deque([_IDENTITY_ELEMENT])
    generators = tuple(sorted(set(generators)))
    while frontier:
        left = frontier.popleft()
        for product in _generator_products(left, generators):
            if product not in subgroup:
                subgroup.add(product)
                frontier.append(product)
    return sum(1 << element for element in subgroup)


def _minimal_generators(group: int) -> tuple[int, ...]:
    generators: list[int] = []
    generated = _IDENTITY_GROUP
    for element in _group_elements(group):
        if generated & (1 << element):
            continue
        generators.append(element)
        generated = _generated(tuple(generators))
    return tuple(generators)


def _group_extensions(group: int) -> tuple[int, ...]:
    generators = _minimal_generators(group)
    return tuple(
        _generated((*generators, element))
        for element in range(24)
        if not group & (1 << element)
    )


@cache
def _all_subgroups() -> tuple[int, ...]:
    known = {_IDENTITY_GROUP}
    frontier = [_IDENTITY_GROUP]
    while frontier:
        group = frontier.pop()
        for candidate in _group_extensions(group):
            if candidate not in known:
                known.add(candidate)
                frontier.append(candidate)
    return tuple(sorted(known, key=lambda group: (-group.bit_count(), group)))


def _subgroups_of(group: int) -> tuple[int, ...]:
    return tuple(
        candidate for candidate in _all_subgroups() if candidate & ~group == 0
    )


@cache
def _block_mapping(block: int, element: int) -> tuple[int, ...]:
    labels = _BLOCK_LABELS[block]
    index = {label: position for position, label in enumerate(labels)}
    return tuple(index[_Q_MAPS[element][label]] for label in labels)


def _apply_block(vector: _Block, block: int, element: int) -> _Block:
    mapping = _block_mapping(block, element)
    result = [0] * len(vector)
    for source, destination in enumerate(mapping):
        result[destination] = vector[source]
    return tuple(result)


def _composition_count(total: int, parts: int) -> int:
    if total < 0 or parts <= 0:
        return 0
    return comb(total + parts - 1, parts - 1)


@cache
def _compositions(total: int, parts: int) -> tuple[_Block, ...]:
    if parts == 1:
        return ((total,),)
    return tuple(
        (first, *suffix)
        for first in range(total + 1)
        for suffix in _compositions(total - first, parts - 1)
    )


def _composition_rank(vector: _Block) -> int | None:
    if not vector or any(value < 0 for value in vector):
        return None
    remaining = sum(vector)
    rank = 0
    for index, value in enumerate(vector[:-1]):
        tail = len(vector) - index - 1
        rank += sum(
            _composition_count(remaining - earlier, tail)
            for earlier in range(value)
        )
        remaining -= value
    return rank


def _composition_unrank(total: int, parts: int, rank: int) -> _Block | None:
    if rank < 0 or rank >= _composition_count(total, parts):
        return None
    remaining = total
    residual_rank = rank
    result: list[int] = []
    for index in range(parts - 1):
        tail = parts - index - 1
        for value in range(remaining + 1):
            count = _composition_count(remaining - value, tail)
            if residual_rank >= count:
                residual_rank -= count
                continue
            result.append(value)
            remaining -= value
            break
    result.append(remaining)
    return tuple(result)


def _stabilizer(vector: _Block, block: int, group: int) -> int:
    return sum(
        1 << element
        for element in _group_elements(group)
        if _apply_block(vector, block, element) == vector
    )


@cache
def _local_classes(
    block: int, mass: int, group: int
) -> tuple[_LocalClass, ...]:
    weight = _BLOCK_WEIGHTS[block]
    if mass % weight != 0:
        return ()
    scalar_mass = mass // weight
    if group == _IDENTITY_GROUP:
        return tuple(
            (vector, _IDENTITY_GROUP)
            for vector in _compositions(scalar_mass, _BLOCK_SIZES[block])
        )
    elements = _group_elements(group)
    result: list[_LocalClass] = []
    for vector in _compositions(scalar_mass, _BLOCK_SIZES[block]):
        representative = min(
            _apply_block(vector, block, item) for item in elements
        )
        if vector == representative:
            result.append((vector, _stabilizer(vector, block, group)))
    return tuple(result)


def _fixed_count(total: int, cycles: tuple[int, ...]) -> int:
    coefficients = [1] + [0] * total
    for cycle in cycles:
        next_coefficients = [0] * (total + 1)
        for degree, coefficient in enumerate(coefficients):
            if coefficient == 0:
                continue
            for addition in range(0, total - degree + 1, cycle):
                next_coefficients[degree + addition] += coefficient
        coefficients = next_coefficients
    return coefficients[total]


@cache
def _remaining_group_weights(block: int, group: int) -> tuple[int, ...]:
    elements = _group_elements(group)
    result: list[int] = []
    for candidate in range(block, _BLOCK_COUNT):
        unseen = set(range(_BLOCK_SIZES[candidate]))
        while unseen:
            seed = min(unseen)
            orbit = {
                _block_mapping(candidate, element)[seed] for element in elements
            }
            unseen -= orbit
            result.append(len(orbit) * _BLOCK_WEIGHTS[candidate])
    return tuple(sorted(result))


@cache
def _free_suffix_count(block: int, total: int, group: int) -> int:
    if block == _BLOCK_COUNT:
        return int(total == 0 and group == _IDENTITY_GROUP)
    exact: dict[int, int] = {}
    for subgroup in _subgroups_of(group):
        fixed = _fixed_count(total, _remaining_group_weights(block, subgroup))
        for larger, value in exact.items():
            is_larger = larger.bit_count() > subgroup.bit_count()
            is_container = subgroup & ~larger == 0
            if is_larger and is_container:
                fixed -= value
        assert fixed >= 0
        exact[subgroup] = fixed
    trivial_assignments = exact[_IDENTITY_GROUP]
    assert trivial_assignments % group.bit_count() == 0
    return trivial_assignments // group.bit_count()


def _block_mass_count(block: int, mass: int, context: _MassContext) -> int:
    suffix_mass, group = context
    if block == 0 or group == _IDENTITY_GROUP:
        weight = _BLOCK_WEIGHTS[block]
        if mass % weight != 0:
            return 0
        local = _composition_count(mass // weight, _BLOCK_SIZES[block])
        return local * _free_suffix_count(block + 1, suffix_mass, group)
    return sum(
        _free_suffix_count(block + 1, suffix_mass, stabilizer)
        for _, stabilizer in _local_classes(block, mass, group)
    )


def _canonicalize_block(
    blocks: list[_Block], block: int, group: int
) -> tuple[_Block, int]:
    candidates = tuple(
        (_apply_block(blocks[block], block, element), element)
        for element in _group_elements(group)
    )
    representative, chosen = min(candidates)
    for index in range(block, _BLOCK_COUNT):
        blocks[index] = _apply_block(blocks[index], index, chosen)
    return representative, _stabilizer(representative, block, group)


def _block_mass(vector: _Block, block: int) -> int:
    return sum(vector) * _BLOCK_WEIGHTS[block]


def _rank_local_block(
    blocks: list[_Block], block: int, context: _MassContext
) -> tuple[int, int] | None:
    suffix_mass, group = context
    vector = blocks[block]
    if block == 0 or group == _IDENTITY_GROUP:
        local_rank = _composition_rank(vector)
        assert local_rank is not None
        suffix = _free_suffix_count(block + 1, suffix_mass, group)
        if suffix == 0:
            return None
        return local_rank * suffix, group
    representative, stabilizer = _canonicalize_block(blocks, block, group)
    result = 0
    for candidate, candidate_stabilizer in _local_classes(
        block, _block_mass(representative, block), group
    ):
        count = _free_suffix_count(block + 1, suffix_mass, candidate_stabilizer)
        if candidate == representative:
            return None if count == 0 else (result, stabilizer)
        result += count
    raise AssertionError


def _extract_blocks(vector: _Vector) -> _Blocks | None:
    if len(vector) != len(_H_ORBITS) or any(value < 0 for value in vector):
        return None
    return tuple(
        tuple(vector[index] for index in labels) for labels in _BLOCK_LABELS
    )


def _build_vector(blocks: _Blocks) -> _Vector:
    result = [0] * len(_H_ORBITS)
    for labels, block in zip(_BLOCK_LABELS, blocks, strict=True):
        for label, value in zip(labels, block, strict=True):
            result[label] = value
    return tuple(result)


def _vector_mass(vector: _Vector) -> int:
    return sum(
        value * len(orbit)
        for value, orbit in zip(vector, _H_ORBITS, strict=True)
    )


def _free_count(total: int) -> int:
    return _free_suffix_count(0, total, _ALL_GROUP)


def _free_rank(vector: _Vector) -> int | None:
    extracted = _extract_blocks(vector)
    if extracted is None:
        return None
    blocks = list(extracted)
    remaining_mass = _vector_mass(vector)
    group = _ALL_GROUP
    rank = 0
    for block in range(_BLOCK_COUNT):
        mass = _block_mass(blocks[block], block)
        rank += sum(
            _block_mass_count(
                block, candidate, (remaining_mass - candidate, group)
            )
            for candidate in range(mass)
        )
        local = _rank_local_block(blocks, block, (remaining_mass - mass, group))
        if local is None:
            return None
        local_rank, group = local
        rank += local_rank
        remaining_mass -= mass
    return rank if group == _IDENTITY_GROUP else None


def _unrank_local_block(
    block: int, mass: int, context: _UnrankContext
) -> tuple[_Block, int, int]:
    suffix_mass, group, rank = context
    if block == 0 or group == _IDENTITY_GROUP:
        suffix = _free_suffix_count(block + 1, suffix_mass, group)
        assert suffix > 0
        local_rank, residual = divmod(rank, suffix)
        weight = _BLOCK_WEIGHTS[block]
        assert mass % weight == 0
        vector = _composition_unrank(
            mass // weight, _BLOCK_SIZES[block], local_rank
        )
        assert vector is not None
        return vector, group, residual
    for vector, stabilizer in _local_classes(block, mass, group):
        count = _free_suffix_count(block + 1, suffix_mass, stabilizer)
        if rank >= count:
            rank -= count
            continue
        return vector, stabilizer, rank
    raise AssertionError


def _free_unrank(total: int, rank: int) -> _Vector | None:
    if rank < 0 or rank >= _free_count(total):
        return None
    blocks: list[_Block] = []
    remaining_mass = total
    group = _ALL_GROUP
    for block in range(_BLOCK_COUNT):
        for mass in range(remaining_mass + 1):
            count = _block_mass_count(
                block, mass, (remaining_mass - mass, group)
            )
            if rank >= count:
                rank -= count
                continue
            vector, group, rank = _unrank_local_block(
                block,
                mass,
                (remaining_mass - mass, group, rank),
            )
            blocks.append(vector)
            remaining_mass -= mass
            break
    assert remaining_mass == 0
    assert rank == 0
    assert group == _IDENTITY_GROUP
    return _build_vector(tuple(blocks))


def test_transposition_normalizer_geometry_is_exact() -> None:
    """H has 24 singleton and 14 paired coordinates in eight S4 blocks."""
    spectrum = {
        size: sum(len(orbit) == size for orbit in _H_ORBITS) for size in (1, 2)
    }
    assert spectrum == _EXPECTED_H_ORBIT_SIZES
    assert _BLOCK_SIZES == _EXPECTED_BLOCK_SIZES
    assert _BLOCK_WEIGHTS == (1, 1, 1, 2, 1, 1, 2, 2)
    assert len(_all_subgroups()) == _EXPECTED_S4_SUBGROUPS


def test_transposition_free_counts_match_reviewed_sequence() -> None:
    """Trivial S4 suffix stabilizer counts give the reviewed free sequence."""
    observed = tuple(_free_count(total) for total in range(_MAXIMUM_MASS + 1))
    assert observed == _EXPECTED_FREE_COUNTS


def test_transposition_free_minus_exact_is_s3_sequence() -> None:
    """The only nonnormalizing free exceptions are the reviewed S3 sequence."""
    difference = tuple(
        free - exact
        for free, exact in zip(
            _EXPECTED_FREE_COUNTS, _EXPECTED_EXACT_COUNTS, strict=True
        )
    )
    assert difference == _EXPECTED_S3_EXCEPTIONS


def test_transposition_free_rank_exhausts_small_domains() -> None:
    """Free normalizer rank is a contiguous bijection through mass five."""
    for total in range(_EXHAUSTIVE_MASS + 1):
        for rank in range(_free_count(total)):
            vector = _free_unrank(total, rank)
            assert vector is not None
            assert _free_rank(vector) == rank


def test_transposition_free_rank_roundtrips_through_fourteen() -> None:
    """Boundary and interior free ranks roundtrip through residual mass 14."""
    for total in range(_MAXIMUM_MASS + 1):
        count = _free_count(total)
        assert _free_unrank(total, -1) is None
        assert _free_unrank(total, count) is None
        if count == 0:
            continue
        for rank in sorted({
            0,
            count // 4,
            count // 2,
            3 * count // 4,
            count - 1,
        }):
            vector = _free_unrank(total, rank)
            assert vector is not None
            assert _free_rank(vector) == rank
