// Copyright:
//   - Copyright © 2026 Alberto Villa Osorno.
// SPDX-License-Identifier:
//   - MIT
// Confidential:
//   - false
// License-File:
//   - LICENSE-MIT
//
// Boundary-Contract:
// - Owns:
//   - POSIX W^X execution evidence for tracked x86-64 initial-halt text.
// - Must-Not:
//   - Serve as a production executable-memory adapter or weaken Rust safety.
// - Allows:
//   - Inputs: generated bytes from the tracked initial-halt COFF fixture.
//   - Outputs: zero on exact hit/miss/null behavior, nonzero on first failure.
//   - Side effects: private mmap, RW-to-RX transition, cache sync, and unmap.
// - Split-When:
//   - Another host ABI or executable-memory policy needs independent evidence.
// - Merge-When:
//   - A tracked production adapter supersedes this development-only harness.
// - Summary:
//   - Executes Windows-x64 initial-halt text through an explicit ABI bridge.
// - Description:
//   - Uses Clang ms_abi so a POSIX x86-64 host passes the state pointer in RCX.
// - Usage:
//   - Compiled by tests/test_native_direct_execution.py with pinned Clang.
// - Defaults:
//   - Never creates RWX memory and never retains executable mappings.
//

//! POSIX W^X execution harness for frozen Windows-x64 initial-halt text.

#define _GNU_SOURCE

#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>

#define MB_NATIVE_POSIX_WINDOWS_X64_BRIDGE
#include "native_region_abi.h"

typedef struct mb_native_region_state NativeRegionState;
typedef mb_native_entry_fn NativeEntry;

static const uint8_t INITIAL_HALT_TEXT[] = {
#include "native_initial_halt_text.inc"
};

_Static_assert(sizeof(NativeRegionState) == 80U, "native ABI size drifted");
_Static_assert(
    offsetof(NativeRegionState, input_consumed) == 32U,
    "input cursor offset drifted");
_Static_assert(
    offsetof(NativeRegionState, output_len) == 56U,
    "output length offset drifted");
_Static_assert(
    offsetof(NativeRegionState, accumulator) == 64U,
    "accumulator offset drifted");
_Static_assert(
    offsetof(NativeRegionState, code_pointer) == 68U,
    "code pointer offset drifted");
_Static_assert(
    offsetof(NativeRegionState, data_pointer) == 72U,
    "data pointer offset drifted");
_Static_assert(
    offsetof(NativeRegionState, termination) == 76U,
    "termination offset drifted");
_Static_assert(sizeof(INITIAL_HALT_TEXT) == 56U, "initial-halt text drifted");

static int execute_initial_halt(void)
{
    const long page = sysconf(_SC_PAGESIZE);
    if (page <= 0L) {
        return 1;
    }
    const size_t page_size = (size_t)page;
    if (sizeof(INITIAL_HALT_TEXT) > SIZE_MAX - (page_size - 1U)) {
        return 2;
    }
    const size_t mapped =
        ((sizeof(INITIAL_HALT_TEXT) + page_size - 1U) / page_size) * page_size;
    void *memory = mmap(
        NULL,
        mapped,
        PROT_READ | PROT_WRITE,
        MAP_PRIVATE | MAP_ANONYMOUS,
        -1,
        0);
    if (memory == MAP_FAILED) {
        return 3;
    }
    memcpy(memory, INITIAL_HALT_TEXT, sizeof(INITIAL_HALT_TEXT));
    if (mprotect(memory, mapped, PROT_READ | PROT_EXEC) != 0) {
        (void)munmap(memory, mapped);
        return 4;
    }
    __builtin___clear_cache(
        (char *)memory,
        (char *)memory + sizeof(INITIAL_HALT_TEXT));

    NativeEntry entry = NULL;
    _Static_assert(sizeof(entry) == sizeof(memory), "function pointer drifted");
    memcpy(&entry, &memory, sizeof(entry));

    NativeRegionState hit = {0};
    if (entry(&hit) != 0U || hit.termination != 1U) {
        (void)munmap(memory, mapped);
        return 5;
    }

    NativeRegionState miss = {0};
    miss.accumulator = 1U;
    const NativeRegionState entry_miss = miss;
    if (entry(&miss) != 1U
        || memcmp(&miss, &entry_miss, sizeof(miss)) != 0) {
        (void)munmap(memory, mapped);
        return 6;
    }

    if (entry(NULL) != 1U) {
        (void)munmap(memory, mapped);
        return 7;
    }
    if (munmap(memory, mapped) != 0) {
        return 8;
    }
    return 0;
}

int main(void)
{
    return execute_initial_halt();
}
