// Copyright:
//   - Copyright © 2026 Alberto Villa Osorno.
// SPDX-License-Identifier:
//   - MIT
// Confidential:
//   - false
// License-File:
//   - LICENSE-MIT
//
// Boundary-Contract:
// - Owns:
//   - POSIX W^X execution evidence for tracked x86-64 no-operation text.
// - Must-Not:
//   - Serve as a production executable-memory adapter or weaken Rust safety.
// - Allows:
//   - Inputs: generated bytes from the tracked no-operation COFF fixture.
//   - Outputs: zero on exact hit/miss behavior, nonzero on first failure.
//   - Side effects: private mmap, RW-to-RX transition, cache sync, and unmap.
// - Split-When:
//   - Another host ABI or executable-memory policy needs independent evidence.
// - Merge-When:
//   - A tracked production adapter supersedes this development-only harness.
// - Summary:
//   - Executes Windows-x64 no-operation text through an explicit ABI bridge.
// - Description:
//   - Proves memory write/register commit and atomic guards under Clang ms_abi.
// - Usage:
//   - Compiled by tests/test_native_direct_execution.py with pinned Clang.
// - Defaults:
//   - Never creates RWX memory and never retains executable mappings.
//

//! POSIX W^X execution harness for frozen Windows-x64 no-operation text.

#define _GNU_SOURCE

#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>

typedef struct NativeRegionState {
    uint32_t *memory;
    uint64_t memory_words;
    uint8_t *input;
    uint64_t input_len;
    uint64_t input_consumed;
    uint8_t *output;
    uint64_t output_capacity;
    uint64_t output_len;
    uint32_t accumulator;
    uint32_t code_pointer;
    uint32_t data_pointer;
    uint8_t termination;
} NativeRegionState;

typedef uint32_t(__attribute__((ms_abi)) *NativeEntry)(NativeRegionState *);

static const uint8_t NO_OPERATION_TEXT[] = {
#include "native_no_operation_text.inc"
};

_Static_assert(sizeof(NativeRegionState) == 80U, "native ABI size drifted");
_Static_assert(
    offsetof(NativeRegionState, memory) == 0U,
    "memory offset drifted");
_Static_assert(
    offsetof(NativeRegionState, memory_words) == 8U,
    "memory words offset drifted");
_Static_assert(
    offsetof(NativeRegionState, input_consumed) == 32U,
    "input cursor offset drifted");
_Static_assert(
    offsetof(NativeRegionState, output_len) == 56U,
    "output length offset drifted");
_Static_assert(
    offsetof(NativeRegionState, accumulator) == 64U,
    "accumulator offset drifted");
_Static_assert(
    offsetof(NativeRegionState, code_pointer) == 68U,
    "code pointer offset drifted");
_Static_assert(
    offsetof(NativeRegionState, data_pointer) == 72U,
    "data pointer offset drifted");
_Static_assert(
    offsetof(NativeRegionState, termination) == 76U,
    "termination offset drifted");
_Static_assert(sizeof(NO_OPERATION_TEXT) == 147U, "no-operation text drifted");

static NativeRegionState entry_state(uint32_t *memory)
{
    NativeRegionState state = {0};
    state.memory = memory;
    state.memory_words = 9U;
    state.input_consumed = UINT64_C(0x0000000123456789);
    state.output_len = UINT64_C(0x000000023456789a);
    state.accumulator = UINT32_C(0xdeadbeef);
    state.code_pointer = 5U;
    state.data_pointer = 7U;
    return state;
}

static int execute_no_operation(void)
{
    const long page = sysconf(_SC_PAGESIZE);
    if (page <= 0L) {
        return 1;
    }
    const size_t page_size = (size_t)page;
    if (sizeof(NO_OPERATION_TEXT) > SIZE_MAX - (page_size - 1U)) {
        return 2;
    }
    const size_t mapped =
        ((sizeof(NO_OPERATION_TEXT) + page_size - 1U) / page_size) * page_size;
    void *code = mmap(
        NULL,
        mapped,
        PROT_READ | PROT_WRITE,
        MAP_PRIVATE | MAP_ANONYMOUS,
        -1,
        0);
    if (code == MAP_FAILED) {
        return 3;
    }
    memcpy(code, NO_OPERATION_TEXT, sizeof(NO_OPERATION_TEXT));
    if (mprotect(code, mapped, PROT_READ | PROT_EXEC) != 0) {
        (void)munmap(code, mapped);
        return 4;
    }
    __builtin___clear_cache(
        (char *)code,
        (char *)code + sizeof(NO_OPERATION_TEXT));

    NativeEntry entry = NULL;
    _Static_assert(sizeof(entry) == sizeof(code), "function pointer drifted");
    memcpy(&entry, &code, sizeof(entry));

    uint32_t hit_memory[9] = {0};
    hit_memory[5] = 77U;
    NativeRegionState hit = entry_state(hit_memory);
    if (entry(&hit) != 0U
        || hit_memory[5] != 65U
        || hit.accumulator != UINT32_C(0xdeadbeef)
        || hit.code_pointer != 6U
        || hit.data_pointer != 8U
        || hit.input_consumed != UINT64_C(0x0000000123456789)
        || hit.output_len != UINT64_C(0x000000023456789a)
        || hit.termination != 0U) {
        (void)munmap(code, mapped);
        return 5;
    }

    uint32_t miss_memory[9] = {0};
    miss_memory[5] = 76U;
    uint32_t miss_memory_before[9] = {0};
    memcpy(miss_memory_before, miss_memory, sizeof(miss_memory));
    NativeRegionState miss = entry_state(miss_memory);
    const NativeRegionState miss_before = miss;
    if (entry(&miss) != 1U
        || memcmp(&miss, &miss_before, sizeof(miss)) != 0
        || memcmp(miss_memory, miss_memory_before, sizeof(miss_memory)) != 0) {
        (void)munmap(code, mapped);
        return 6;
    }

    uint32_t short_memory[9] = {0};
    short_memory[5] = 77U;
    NativeRegionState short_state = entry_state(short_memory);
    short_state.memory_words = 8U;
    const NativeRegionState short_before = short_state;
    if (entry(&short_state) != 1U
        || memcmp(&short_state, &short_before, sizeof(short_state)) != 0
        || short_memory[5] != 77U) {
        (void)munmap(code, mapped);
        return 7;
    }

    NativeRegionState null_memory = entry_state(NULL);
    const NativeRegionState null_memory_before = null_memory;
    if (entry(&null_memory) != 1U
        || memcmp(
            &null_memory, &null_memory_before, sizeof(null_memory)) != 0) {
        (void)munmap(code, mapped);
        return 8;
    }
    if (entry(NULL) != 1U) {
        (void)munmap(code, mapped);
        return 9;
    }
    if (munmap(code, mapped) != 0) {
        return 10;
    }
    return 0;
}

int main(void)
{
    return execute_no_operation();
}
